<template>
  <DesktopHeader /><view class="page"><view v-if="order" class="container detail-layout">
    <view class="blocks">
      <view v-if="order.readOnly" class="card"><h3>历史订单 · 只读</h3><text class="muted">仅展示已获取的信息；缺少明细不代表商品数量或金额为零。此订单暂不提供支付或售后操作。</text></view>
      <view class="card status-card"><h2>{{ labels[order.status] || order.status }}</h2><text>{{ statusNotes[order.status] || '可在本页查看订单进度。' }}</text></view>
      <view v-if="order.shipments?.length" class="card"><h3>物流与包裹</h3><view v-for="(ship,index) in order.shipments" :key="ship.id" class="block"><b>包裹 {{ Number(index)+1 }} · {{ ship.logisticsCompany || '承运商待补充' }}</b><text selectable>{{ ship.trackingNo || '单号待补充' }}</text><text class="muted">{{ date(ship.shippedAt) }}</text><text v-for="line in (ship.items || [])" :key="line.orderItemId">{{ shipmentItemName(line.orderItemId) }} × {{ line.quantity }}</text><text v-if="!ship.items?.length" class="muted">包裹商品明细未获取</text><view v-for="(trace,i) in shipmentTraces(ship)" :key="i">{{ trace.description || trace.context || '轨迹说明未获取' }} {{ date(trace.time) }}</view><text v-if="!shipmentTraces(ship).length" class="muted">物流轨迹未获取，登记单号不代表已签收。</text></view></view>
      <view class="card"><h3>收货信息</h3><b>{{ order.recipientName || '收货人未获取' }} {{ order.recipientMobile || '联系方式未获取' }}</b><view v-if="order.addressDetail">{{ order.province }}{{ order.city }}{{ order.district }}{{ order.addressDetail }}</view><view v-else class="muted">收货地址未获取</view></view>
      <view class="card"><h3>商品信息</h3><view v-if="orderItemSummary(order).quantity === null" class="muted">商品明细与数量未获取</view><view v-for="item in orderItemSummary(order).items" :key="item.id" class="item"><image v-if="item.imageSnapshot" :src="item.imageSnapshot" mode="aspectFit"/><view v-else class="no-image">暂无图片</view><view><b>{{ item.nameSnapshot || '商品名称未获取' }}</b><text class="muted">{{ item.specificationSnapshot }}</text><text>{{ money(item.unitPriceCents) }} × {{ item.quantity }}</text><text v-if="item.review" class="muted">已评价 · {{ item.review.rating }} 星</text><button v-else-if="reviewable(item)" size="mini" :disabled="busy" @click="openReview(item)">评价商品</button></view></view></view>
      <view v-if="reviewItem" class="card"><h3>商品评价</h3><picker :range="['1星','2星','3星','4星','5星']" :value="rating-1" :disabled="busy" @change="rating=Number($event.detail.value)+1"><view class="input">评分：{{ rating }} 星</view></picker><textarea v-model="reviewText" :disabled="busy" class="textarea" maxlength="2000" placeholder="分享真实使用体验"/><button class="primary-btn" :disabled="busy" @click="review">提交评价</button><button class="outline-btn" :disabled="busy" @click="reviewItem=''">取消</button></view>
      <view v-if="order.afterSales?.length" class="card"><h3>售后进度</h3><view v-for="sale in order.afterSales" :key="sale.id" class="block"><b>{{ afterLabels[sale.status] || sale.status }} · {{ saleTypes[sale.type] || '商品售后' }}</b><text selectable>{{ sale.afterSaleNo }}</text><text>{{ sale.reason }}</text><text v-for="line in (sale.items || [])" :key="line.orderItemId">{{ shipmentItemName(line.orderItemId) }} × {{ line.quantity }}</text><text v-if="!sale.items?.length" class="muted">售后商品明细未获取</text><text>申请现金退款 {{ money(sale.requestedCents) }} · 预计返还积分抵扣 {{ money(sale.pointReturnCents) }}</text><text v-for="refund in (sale.refunds || [])" :key="refund.id">{{ refundLabels[refund.status] || '退款状态待核实' }} · {{ money(refund.amountCents) }}</text><text v-if="sale.status==='REFUNDING' && !sale.refunds?.length" class="muted">退款结果待确认</text><ImageEvidencePicker v-if="saleEvidenceIds(sale.evidenceImages).length" :model-value="saleEvidenceIds(sale.evidenceImages)" readonly/><text v-if="sale.returnTrackingNo" selectable>退货单号 {{ sale.returnTrackingNo }}</text><button v-if="returnable(sale)" size="mini" :disabled="busy" @click="editReturn(sale)">{{ sale.returnTrackingNo ? '更新寄回物流' : '填写寄回物流' }}</button></view></view>
      <view v-if="returnSale" class="card"><h3>登记退货物流</h3><text class="muted">请按审核要求寄回。填写单号不会自动确认收货或退款。</text><input v-model="returnCompany" :disabled="busy" class="input" maxlength="80" placeholder="退货物流公司"/><input v-model="returnTracking" :disabled="busy" class="input" maxlength="100" placeholder="退货运单号"/><button class="primary-btn" :disabled="busy" @click="saveReturn">保存寄回信息</button><button class="outline-btn" :disabled="busy" @click="returnSale=null">取消填写</button></view>
    </view>
    <view class="card aside"><view class="line"><text>订单号</text><b selectable>{{ order.orderNo }}</b></view><view class="line"><text>商品金额</text><b>{{ money(order.subtotalCents) }}</b></view><view class="line"><text>优惠券</text><b>-{{ money(order.discountCents) }}</b></view><view class="line"><text>积分抵扣</text><b>-{{ money(order.pointDiscountCents) }}</b></view><view class="line"><text>运费</text><b>{{ money(order.shippingCents) }}</b></view><view class="line total"><text>{{ order.paidAt ? '支付金额' : '现金应付' }}</text><b>{{ money(order.payableCents) }}</b></view>
      <template v-if="can('PAY')"><view class="payment-options"><button v-for="option in channels" :key="option.channel" :class="channel===option.channel?'selected':''" :disabled="!option.enabled || busy" @click="channel=option.channel">{{ paymentLabels[option.channel] }}<text v-if="!option.enabled" class="muted"> · 暂不可用</text></button><view v-if="!channels.some(x=>x.enabled)" class="muted">支付暂不可用，订单已保存，请稍后重试。</view></view><button class="primary-btn" :disabled="busy || !channel" @click="pay">{{ busy ? '正在处理…' : '继续支付' }}</button></template>
      <view v-if="qr" class="qr"><image :src="qr" mode="aspectFit"/><text>请使用微信扫码，支付后点击查询结果。</text></view><view v-if="paymentNote" role="status" class="notice">{{ paymentNote }}</view>
      <button class="outline-btn" :disabled="busy" @click="checkPayment">刷新订单状态</button><button v-if="can('CANCEL')" class="outline-btn" :disabled="busy" @click="action('cancel','确定取消此订单？积分和优惠券按服务端规则释放。')">取消订单</button><button v-if="can('CONFIRM_RECEIPT')" class="primary-btn" :disabled="busy" @click="action('receipt','确认已收到商品？')">确认收货</button><button v-if="can('APPLY_AFTER_SALE')" class="outline-btn" @click="afterSale">申请商品售后</button><view v-if="order.unavailableReason" class="muted">{{ order.unavailableReason }}</view>
      <button class="outline-btn" :disabled="busy" @click="viewOrders">查看全部订单</button>
    </view>
  </view><view v-else class="empty card">{{ error || '正在读取订单…' }}<button v-if="error" @click="load">重新加载</button></view></view>
</template>
<script setup lang="ts">
defineOptions({ inheritAttrs: false });
import { onLoad,onShow,onHide,onUnload } from '@dcloudio/uni-app';
import { computed,ref } from 'vue';
import DesktopHeader from '../../components/DesktopHeader.vue';
import ImageEvidencePicker from '../../components/ImageEvidencePicker.vue';
function saleEvidenceIds(value:unknown):string[]{return Array.isArray(value)?[...new Set(value.filter((ref):ref is string=>typeof ref==='string'&&/^file:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(ref)).map(ref=>ref.slice(5).toLowerCase()))].slice(0,9):[];}
import { api,money,toast,requireLogin,mallSessionStamp } from '../../api';
import { channelsForEnvironment,orderItemSummary } from '../../commerce-model';
import { confirmPayment,createOrderPayment,invokePayment,paymentEnvironment,paymentLabels } from '../../payments';
const id=ref(''),order=ref<any>(null),error=ref(''),capabilities=ref<any>({payments:[]}),busy=ref(false),channel=ref(''),qr=ref(''),paymentNote=ref(''),paymentId=ref(''),reviewItem=ref(''),reviewText=ref(''),rating=ref(5);
let poll:ReturnType<typeof setInterval>|undefined, polls=0,screen=0,loadRevision=0,visible=true,loadedSession='';
const returnSale=ref<any>(null),returnCompany=ref(''),returnTracking=ref('');
function context(){return {screen,session:loadedSession,id:order.value?.id||id.value};}
function current(ctx:ReturnType<typeof context>){return visible && ctx.screen===screen && !!ctx.session && ctx.session===mallSessionStamp();}
function returnable(sale:any){return !order.value?.readOnly && sale?.executionOwner==='NEW_SYSTEM' && sale.status==='WAITING_RETURN' && ['RETURN_REFUND','EXCHANGE'].includes(sale.type);}
function editReturn(sale:any){if(busy.value||!current(context())||!returnable(sale))return;returnSale.value=sale;returnCompany.value=sale.returnLogisticsCompany||'';returnTracking.value=sale.returnTrackingNo||'';}
async function saveReturn(){const ctx=context(),sale=returnSale.value;if(busy.value||!current(ctx)||!returnable(sale))return;if(!returnCompany.value.trim()||!returnTracking.value.trim())return toast('请填写物流公司和运单号');busy.value=true;try{await api('/storefront/orders/'+encodeURIComponent(ctx.id)+'/after-sales/'+encodeURIComponent(sale.id)+'/return-logistics',{method:'POST',auth:true,sessionStamp:ctx.session,data:{logisticsCompany:returnCompany.value.trim(),trackingNo:returnTracking.value.trim(),version:sale.version}});if(!current(ctx))return;returnSale.value=null;await load();if(current(ctx))toast('寄回信息已保存，等待后台收货审核');}catch(e){if(current(ctx))toast(e);}finally{if(current(ctx))busy.value=false;}}
const channels=computed(()=>channelsForEnvironment(capabilities.value.payments || [],paymentEnvironment(),uni.getSystemInfoSync().windowWidth>=900));
const labels:Record<string,string>={PENDING_PAYMENT:'等待付款',PAID:'支付成功',ERP_SYNCING:'履约处理中',WAITING_FULFILLMENT:'等待发货',SHIPPED:'已发货',RECEIVED:'已签收',COMPLETED:'已完成',CANCELLED:'已取消',AFTER_SALE:'售后处理中',REFUNDED:'已退款',CLOSED:'已关闭'};
const statusNotes:Record<string,string>={PENDING_PAYMENT:'订单已保存，可继续支付；请勿重复下单。',PAID:'付款成功，请耐心等待发货。',ERP_SYNCING:'正在安排发货，请耐心等待。',WAITING_FULFILLMENT:'正在安排发货，请耐心等待。',SHIPPED:'商品已发货，请查看包裹物流；全部收到后可确认收货。',RECEIVED:'订单已确认收货，欢迎分享使用体验。',COMPLETED:'订单已完成，感谢您的购买。',CANCELLED:'订单已取消，可返回商城继续选购。',AFTER_SALE:'售后正在处理中，可在下方查看进度。',REFUNDED:'订单已退款，可在下方查看退款记录。',CLOSED:'订单已关闭，如需帮助请联系客服。'};
const afterLabels:Record<string,string>={APPLIED:'待审核',REVIEWING:'审核中',APPROVED:'已批准',PROCESSING:'处理中',WAITING_RETURN:'待寄回',RETURNED:'退货已收货',REFUNDING:'退款中',COMPLETED:'已完成',REJECTED:'已拒绝',CANCELLED:'已取消',ERP_SYNCING:'处理中'};
const saleTypes:Record<string,string>={REFUND_ONLY:'仅退款',RETURN_REFUND:'退货退款',EXCHANGE:'换货'},refundLabels:Record<string,string>={CREATED:'退款已提交',PROCESSING:'退款处理中',SUCCEEDED:'已退款',FAILED:'退款失败，待处理',CLOSED:'退款已关闭'};
onLoad(o=>{id.value=String(o?.id||'');});
onShow(()=>{reset();visible=true;void load();});onHide(reset);onUnload(reset);
function reset(){stopPoll();screen++;loadRevision++;visible=false;loadedSession='';order.value=null;error.value='';capabilities.value={payments:[]};paymentId.value='';qr.value='';paymentNote.value='';channel.value='';reviewItem.value='';reviewText.value='';rating.value=5;returnSale.value=null;returnCompany.value='';returnTracking.value='';busy.value=false;}
function can(action:string){return !order.value?.readOnly && (order.value?.allowedActions?.includes(action) || false);}
async function load(){const session=mallSessionStamp();if(loadedSession && loadedSession!==session){reset();visible=true;}const ctx={screen,session,id:id.value},request=++loadRevision;if(!requireLogin('/pages/order-detail/index?id='+encodeURIComponent(id.value)))return;try{error.value='';const [value,config]=await Promise.all([api<any>('/storefront/orders/'+encodeURIComponent(ctx.id),{auth:true,sessionStamp:session}),api('/storefront/capabilities')]);if(!current(ctx)||request!==loadRevision)return;loadedSession=session;order.value=value;capabilities.value=config;channel.value=channels.value.find(x=>x.enabled)?.channel||'';const pending=value.paymentIntents?.find((x:any)=>['CREATED','PENDING'].includes(x.status));paymentId.value=pending?.id || '';if(value.status!=='PENDING_PAYMENT'){qr.value='';stopPoll();}}catch(e){if(current(ctx)&&request===loadRevision){order.value=null;error.value=e instanceof Error?e.message:String(e);}}}
function stopPoll(){if(poll)clearInterval(poll);poll=undefined;}
async function checkPayment(){const ctx=context();if(!current(ctx))return;try{if(paymentId.value){const result=await confirmPayment(paymentId.value);if(!current(ctx))return;paymentNote.value=result.paid?'支付已确认。':'付款结果确认中，请稍后查询，无需重新下单。';if(result.paid)stopPoll();}if(current(ctx))await load();}catch(e){if(current(ctx))toast(e);}}
async function pay(){const ctx=context();if(busy.value||!channel.value||!current(ctx)||!can('PAY'))return;busy.value=true;try{const payment:any=await createOrderPayment(ctx.id,channel.value);if(!current(ctx))return;paymentId.value=payment.id;if(payment.status?.toLowerCase()!=='pending'){await checkPayment();return;}const result=await invokePayment(payment.invoke);if(!current(ctx))return;qr.value=result.qr||'';paymentNote.value='已发起支付，正在等待服务端确认。';await checkPayment();if(!current(ctx))return;stopPoll();polls=0;if(order.value?.status==='PENDING_PAYMENT')poll=setInterval(()=>{if(!current(ctx)||++polls>24){stopPoll();return;}void checkPayment();},5000);}catch(e){if(current(ctx)){toast(e);paymentNote.value='支付未完成，可留在本页查询或稍后从订单继续支付。';await load();}}finally{if(current(ctx))busy.value=false;}}
async function action(path:string,content:string){const ctx=context(),permission=path==='cancel'?'CANCEL':path==='receipt'?'CONFIRM_RECEIPT':'';if(busy.value||!current(ctx)||!can(permission))return;const answer=await uni.showModal({title:'订单操作',content});if(!answer.confirm||busy.value||!current(ctx)||!can(permission))return;busy.value=true;try{await api('/storefront/orders/'+encodeURIComponent(ctx.id)+'/'+path,{method:'POST',auth:true,sessionStamp:ctx.session});if(current(ctx))await load();}catch(e){if(current(ctx))toast(e);}finally{if(current(ctx))busy.value=false;}}
function afterSale(){if(current(context())&&can('APPLY_AFTER_SALE'))uni.navigateTo({url:'/pages/after-sale/index?orderId='+encodeURIComponent(order.value.id||id.value)});}
function viewOrders(){uni.redirectTo({url:'/pages/orders/index'});}
function reviewable(item:any){return !order.value?.readOnly && !item?.review && ['RECEIVED','COMPLETED','CLOSED'].includes(order.value?.status);}
function openReview(item:any){if(busy.value||!current(context())||!reviewable(item))return;reviewItem.value=item.id;reviewText.value='';rating.value=5;}
async function review(){const ctx=context(),item=order.value?.items?.find((row:any)=>row.id===reviewItem.value);if(busy.value||!current(ctx)||!item||!reviewable(item))return;if(!reviewText.value.trim())return toast('请填写评价内容');busy.value=true;try{const value=await api('/storefront/reviews',{method:'POST',auth:true,sessionStamp:ctx.session,data:{orderItemId:item.id,rating:rating.value,content:reviewText.value.trim(),images:[]}});if(!current(ctx))return;item.review=value;reviewItem.value='';reviewText.value='';toast('评价已提交');}catch(e){if(current(ctx))toast(e);}finally{if(current(ctx))busy.value=false;}}
function date(value:unknown){const parsed=value?new Date(String(value)):null;return parsed&&Number.isFinite(parsed.getTime())?parsed.toLocaleString():'时间未获取';}
function shipmentTraces(ship:any){const value=ship.traceJson??ship.traces;const rows=Array.isArray(value)?value:Array.isArray(value?.data)?value.data:[];return rows.filter((row:any)=>row&&typeof row==='object'&&!Array.isArray(row));}
function shipmentItemName(itemId:string){const item=order.value?.items?.find((row:any)=>row.id===itemId);return item?[item.nameSnapshot,item.specificationSnapshot].filter(Boolean).join(' · '):'商品明细未获取';}
</script>
<style scoped lang="scss">
.blocks,.card,.item>view{min-width:0}.block{overflow-wrap:anywhere}.blocks button{min-height:44px;height:auto;line-height:1.5;padding:10px;font-size:14px}
.detail-layout,.blocks{display:grid;gap:18px}.card h2,.card h3{margin:0 0 16px}.status-card{border-top:4px solid var(--green)}.status-card text,.muted{font-size:14px;line-height:1.7}.block{padding:14px 0;border-top:1px solid var(--line)}.block text,.item text{display:block;margin-top:6px}.item{display:grid;grid-template-columns:90px 1fr;gap:16px;padding:16px 0;border-top:1px solid var(--line)}.item image,.no-image{width:90px;height:90px}.no-image{background:#f5f5f5;display:grid;place-items:center;font-size:12px;color:var(--muted)}.line{display:flex;justify-content:space-between;gap:15px;margin-bottom:16px;font-size:14px}.line b{max-width:68%;overflow-wrap:anywhere;text-align:right}.total{border-top:1px solid var(--line);padding-top:16px}.total b{color:#be092d;font-size:24px}.aside button{margin-top:12px;font-size:15px;min-height:44px;height:auto;padding:12px}.payment-options button{background:#f6f8fb;text-align:left;border:1px solid var(--line);border-radius:6px;line-height:1.6}.payment-options .selected{border-color:var(--green)}.qr{display:grid;justify-items:center;gap:10px;font-size:14px;margin-top:16px}.qr image{width:240px;height:240px}.notice{background:#eef6ff;padding:12px;margin-top:12px;line-height:1.7;font-size:14px}.textarea{margin:12px 0}@media(min-width:900px){.detail-layout{grid-template-columns:minmax(0,1fr) 360px;align-items:start}.aside{position:sticky;top:108px}}
</style>
