import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import vm from 'node:vm';
const require=createRequire(import.meta.url),ts=require('typescript'),vue=require('vue');
const {parse,compileScript,compileTemplate}=require('vue/compiler-sfc');
const id='12345678-1234-4234-8234-123456789012',file={path:'blob:synthetic-local',size:4,type:'image/png'},receipt={id,byteSize:4,contentType:'image/png',sha256:'a'.repeat(64)};
function evaluate(source,imports,globals={}){const module={exports:{}};vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,Error,URL,AbortController,...globals,require(name){assert.ok(Object.hasOwn(imports,name),'Unexpected import '+name);return imports[name];}});return module.exports;}
function fixture(options={}){let stamp='a',token='synthetic-token';const uploads=[],fetches=[],revoked=[],aborted=[];const user={id:'member-a'};
 class LocalURL extends URL {static createObjectURL(){return 'blob:private-test';}static revokeObjectURL(url){revoked.push(url);}}
 const exported=evaluate(readFileSync(new URL('../src/after-sale-images.ts',import.meta.url),'utf8'),{'./api':{API_BASE:options.base||'/global/api/saidian-mall/v1',mallSessionStamp:()=>stamp,api:()=>Promise.resolve({enabled:options.enabled!==false})},'./realm':{isGlobalMall:true,mallStorage:{get:key=>key==='saidian-user'?user:key==='saidian-token'?token:null}}},{window:{location:{origin:'https://shop.example.test'}},URL:LocalURL,uni:{uploadFile(input){uploads.push(input);return {abort(){aborted.push(true);input.fail();},onProgressUpdate(callback){input.progress=callback;}}}},fetch:async(url,input)=>{fetches.push({url,input});return options.fetch?options.fetch(url,input):{ok:true,status:200,headers:{get:()=> 'image/png'},blob:async()=>({size:4})};}});
 return {exported,client:exported.createAfterSaleImageClient(),uploads,fetches,revoked,aborted,user,switch(){stamp='b';token='other-token';}};
}
test('validates size/type/count and duplicate IDs without uploading invalid selections',()=>{const h=fixture();for(const value of [{...file,size:0},{...file,size:10485761},{...file,type:'image/svg+xml'}])assert.throws(()=>h.exported.evidenceFile(value));assert.deepEqual(JSON.parse(JSON.stringify(h.exported.evidenceFile(file))),file);assert.equal(h.exported.validEvidenceIds([id]),true);for(const value of [[id,id],['file:'+id],Array(10).fill(id),['https://bad.test/image']])assert.equal(h.exported.validEvidenceIds(value),false);assert.equal(h.uploads.length,0);});
test('uploads only to fixed same-origin endpoint with bearer header, progress and validated private receipt',async()=>{const h=fixture(),progress=[];const pending=h.client.upload(file,value=>progress.push(value));assert.equal(h.uploads[0].url,'https://shop.example.test/global/api/saidian-mall/v1/storefront/after-sale-images');assert.equal(h.uploads[0].header.Authorization,'Bearer synthetic-token');assert.equal(h.uploads[0].name,'file');h.uploads[0].progress({progress:45});h.uploads[0].success({statusCode:201,data:JSON.stringify(receipt)});assert.deepEqual(JSON.parse(JSON.stringify(await pending)),receipt);assert.deepEqual(progress,[45]);});
test('rejects foreign destination, temporary account and invalid receipt; 401 never refreshes or logs out',async()=>{const bad=fixture({base:'https://foreign.example.test/api'});await assert.rejects(bad.client.upload(file,()=>{}),/地址不安全/);assert.equal(bad.uploads.length,0);const tmp=fixture();tmp.user.phoneTestMode=true;await assert.rejects(tmp.client.upload(file,()=>{}),/已验证/);for(const response of [{statusCode:401,data:'{}'},{statusCode:201,data:JSON.stringify({...receipt,id:'https://bad.test'})},{statusCode:201,data:JSON.stringify({...receipt,byteSize:3})}]){const h=fixture(),pending=h.client.upload(file,()=>{});h.uploads[0].success(response);await assert.rejects(pending);assert.equal(h.client.isCurrent(),true);}});
test('account change discards late upload response and cancel aborts pending task',async()=>{const h=fixture(),pending=h.client.upload(file,()=>{});h.switch();h.uploads[0].success({statusCode:200,data:JSON.stringify(receipt)});await assert.rejects(pending,/账号/);const other=fixture(),request=other.client.upload(file,()=>{});other.client.cancel();await assert.rejects(request);assert.equal(other.aborted.length,1);});
test('private preview forbids redirects, sends no token in URL, returns blob URL and revokes it',async()=>{const h=fixture(),url=await h.client.preview(id);assert.equal(url,'blob:private-test');assert.equal(h.fetches[0].input.redirect,'error');assert.equal(h.fetches[0].input.credentials,'omit');assert.equal(h.fetches[0].url.includes('token'),false);assert.equal(h.fetches[0].input.headers.Authorization,'Bearer synthetic-token');h.client.cancel();assert.deepEqual(h.revoked,[url]);await assert.rejects(h.client.preview(id));});
test('download ignores late account response and rejects non-image or oversize payload',async()=>{let resolve;const h=fixture({fetch:()=>new Promise(r=>resolve=r)}),pending=h.client.preview(id);h.switch();resolve({ok:true,status:200,headers:{get:()=> 'image/png'},blob:async()=>({size:4})});await assert.rejects(pending,/账号/);for(const [type,size] of [['text/html',4],['image/png',10485761]]){const x=fixture({fetch:async()=>({ok:true,status:200,headers:{get:()=>type},blob:async()=>({size})})});await assert.rejects(x.client.preview(id));}});

const filename='ImageEvidencePicker.vue',descriptor=parse(readFileSync(new URL('../src/components/ImageEvidencePicker.vue',import.meta.url),'utf8'),{filename}).descriptor,script=compileScript(descriptor,{id:'images'}),template=compileTemplate({source:descriptor.template.content,filename,id:'images',compilerOptions:{bindingMetadata:script.bindings,isCustomElement:tag=>tag===tag.toLowerCase()}});assert.deepEqual(template.errors,[]);const render=evaluate(template.code,{vue:{...vue,withDirectives:node=>node}}).render;
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function picker(options={}){const hooks={},events=[],calls=[],releases=[],uploads=[];let alive=true;const props=vue.reactive({modelValue:options.ids||[],locked:!!options.locked,readonly:!!options.readonly});const client={isCurrent:()=>alive,cancel(){alive=false;},release:url=>releases.push(url),capabilities:async()=>{calls.push(['capabilities']);if(options.capabilityError)throw options.capabilityError;return {enabled:options.enabled!==false,reason:options.reason||'未配置'};},preview:async value=>{calls.push(['preview',value]);if(options.previewError)throw options.previewError;return 'blob:private-'+value;},upload:async(value,progress)=>{calls.push(['upload',value]);return new Promise((resolve,reject)=>uploads.push({resolve,reject,progress}));}};const actual=fixture().exported;
 const component=evaluate(script.content,{vue:{...vue,onMounted:callback=>hooks.mount=callback,onBeforeUnmount:callback=>hooks.unmount=callback},'../after-sale-images':{...actual,createAfterSaleImageClient:()=>client}},{uni:{chooseImage(input){calls.push(['choose',input.count]);input.success({tempFiles:options.files||[file]});input.complete();}},setInterval:callback=>{hooks.timer=callback;return 1;},clearInterval(){}}).default;
 const state=component.setup(props,{emit:(...args)=>events.push(args),expose(){}}),ui=vue.proxyRefs(state);return {state,props,events,calls,uploads,releases,hooks,tree:()=>render(props,[],props,ui,{},{}),switch(){alive=false;},async mount(){await hooks.mount();await tick();}};
}
test('real picker marks failed upload as blocking, retries same selected file then emits successful ID only',async()=>{const h=picker();await h.mount();h.state.choose();assert.equal(h.state.rows.value.length,1);assert.equal(h.events.at(-1)[0],'blocked');assert.equal(h.events.at(-1)[1],true);h.uploads[0].progress(50);assert.equal(h.state.rows.value[0].progress,50);h.uploads[0].reject(Error('synthetic failure'));await tick();assert.equal(h.state.rows.value[0].status,'failed');h.state.retry(h.state.rows.value[0]);h.uploads[1].resolve(receipt);await tick();assert.equal(h.state.rows.value[0].status,'done');assert.deepEqual(JSON.parse(JSON.stringify(h.events.filter(e=>e[0]==='update:modelValue').at(-1)[1])),[id]);assert.equal(h.events.filter(e=>e[0]==='blocked').at(-1)[1],false);assert.equal(h.state.rows.value[0].src,'blob:private-'+id);});
test('picker recovers existing IDs privately without uploading and frozen state blocks selection/removal/retry',async()=>{const h=picker({ids:[id],locked:true});await h.mount();assert.equal(h.state.rows.value[0].id,id);assert.equal(h.state.rows.value[0].src,'blob:private-'+id);h.state.choose();h.state.remove(h.state.rows.value[0]);h.state.retry(h.state.rows.value[0]);assert.equal(h.state.rows.value.length,1);assert.equal(h.calls.some(c=>c[0]==='upload'||c[0]==='choose'),false);h.hooks.unmount();assert.ok(h.releases.includes('blob:private-'+id));});
test('picker disables unavailable service, caps selections at 9, removes failures and discards changed-session response',async()=>{const disabled=picker({enabled:false});await disabled.mount();disabled.state.choose();assert.deepEqual(disabled.calls,[['capabilities']]);const h=picker({files:Array(12).fill(file)});await h.mount();h.state.choose();assert.equal(h.state.rows.value.length,9);h.state.choose();assert.equal(h.calls.filter(x=>x[0]==='choose').length,1);h.state.remove(h.state.rows.value[0]);assert.equal(h.state.rows.value.length,8);h.switch();h.hooks.timer();assert.equal(h.state.rows.value.length,0);for(const upload of h.uploads)upload.resolve(receipt);await tick();assert.equal(h.state.rows.value.length,0);assert.equal(h.events.filter(e=>e[0]==='update:modelValue').some(e=>e[1].length>0),false);});
test('readonly submitted evidence downloads privately without capabilities or edit controls',async()=>{const h=picker({readonly:true,ids:[id]});await h.mount();h.state.enabled.value=true;h.state.choose();h.state.remove(h.state.rows.value[0]);assert.deepEqual(h.calls,[['preview',id]]);assert.equal(h.state.rows.value.length,1);const tree=JSON.stringify(h.tree(),(key,value)=>key==='component'||key==='appContext'?undefined:typeof value==='symbol'?String(value):value);assert.match(tree,/售后图片/);assert.equal(tree.includes('添加问题图片'),false);assert.equal(tree.includes('申请结果待确认'),false);assert.equal(tree.includes('移除'),false);});
test('capability failure and disabled reason always use friendly copy without blocking text-only submission',async()=>{for(const options of [{enabled:false,reason:'未配置 OBJECT_STORAGE_SECRET'},{capabilityError:Error('Cannot GET /storefront/after-sale-images/capabilities')}]){const h=picker(options);await h.mount();assert.equal(h.state.notice.value,'暂时无法添加图片，您仍可提交文字说明。');assert.equal(h.state.enabled.value,false);h.state.choose();assert.equal(h.calls.some(row=>row[0]==='choose'),false);assert.equal(h.events.some(row=>row[0]==='blocked'&&row[1]===true),false);}const actual=fixture({enabled:false});assert.equal((await actual.client.capabilities()).reason,'暂时无法添加图片，您仍可提交文字说明。');});
test('upload and private-preview technical errors never appear in rendered customer messages',async()=>{const h=picker();await h.mount();h.state.choose();h.uploads[0].reject(Error('SyntaxError: Cannot POST /private/upload at storage.ts:99'));await tick();assert.equal(h.state.rows.value[0].error,'图片上传失败，请重试或移除。');assert.equal(h.state.rows.value[0].status,'failed');const preview=picker({readonly:true,ids:[id],previewError:Error('TypeError: Failed to fetch /private/images')});await preview.mount();assert.equal(preview.state.rows.value[0].error,'图片暂时无法读取，请稍后重试。');assert.equal(preview.state.rows.value[0].src,'');});
