<template><DesktopHeader/><view class="page"><view class="container points"><view class="card"><h2>我的积分</h2><text class="muted">可抵扣商品金额（不抵运费）</text><view class="balance">{{ money(data?.balanceCents) }}</view><text class="muted">{{ data?.reason || '使用 pointCents 展示抵扣金额，不换算旧系统积分单位。' }}</text></view><view class="card"><h3>积分流水</h3><view v-if="error" class="muted">{{ error }}</view><view v-for="item in items" :key="item.id" class="ledger" @click="openOrder(item.orderId)"><view><b>{{ labels[item.type] || item.type }}</b><text>{{ new Date(item.createdAt).toLocaleString() }}</text></view><b>{{ item.deltaCents>=0?'+':'−' }}{{ money(Math.abs(item.deltaCents)) }}</b></view><view v-if="!items.length && !busy" class="empty">暂无已记录流水</view><button v-if="data?.pagination?.hasMore" class="outline-btn" :disabled="busy" @click="load(true)">加载更多</button></view></view></view></template>
<script setup lang="ts">
import {onShow} from '@dcloudio/uni-app';import{ref}from'vue';import DesktopHeader from '../../components/DesktopHeader.vue';import{api,money}from'../../api';
const data=ref<any>(),items=ref<any[]>([]),error=ref(''),busy=ref(false);let page=1;
const labels:Record<string,string>={ORDER_DEDUCT:'订单抵扣',ORDER_REDEMPTION:'订单积分抵扣',ORDER_CANCEL_RETURN:'取消订单返还',AFTER_SALE_RETURN:'商品售后返还',FULL_REFUND_RETURN:'原退款返还',DEMO_TEST_CREDIT:'隔离演示测试额度'};
onShow(()=>{page=1;items.value=[];data.value=undefined;void load();});
async function load(more=false){if(busy.value)return;busy.value=true;error.value='';const next=more?page+1:1;try{data.value=await api('/storefront/points?page='+next,{auth:true});items.value=more?[...items.value,...data.value.items]:data.value.items;page=next;}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{busy.value=false;}}
function openOrder(id?:string){if(id)uni.navigateTo({url:'/pages/order-detail/index?id='+encodeURIComponent(id)});}
</script>
<style scoped>.points{max-width:850px;display:grid;gap:20px}.card h2,.card h3{margin:0 0 18px}.balance{font-size:36px;color:#be092d;margin:20px 0}.muted{font-size:14px;line-height:1.7}.ledger{display:flex;justify-content:space-between;gap:20px;padding:18px 0;border-top:1px solid var(--line);font-size:15px}.ledger text{display:block;color:var(--muted);font-size:13px;margin-top:8px}</style>
