<template><DesktopHeader/><view class="page"><view class="container card form"><h2>申请商品售后</h2><view v-if="error" class="notice" role="alert">{{ error }}</view><button v-if="error && !frozen" class="outline-btn" :disabled="busy" @click="load">刷新订单与剩余额度</button><template v-if="order"><view class="muted">选择商品与数量，现金退款和积分返还将根据原订单分摊计算。已完成和处理中的申请会占用可退额度。</view><view v-for="item in lines" :key="item.id" class="item"><b>{{ item.nameSnapshot }}</b><view class="muted">{{ item.specificationSnapshot }}</view><view v-if="item.available.quantityRemaining" class="quantity"><text>剩余可申请 {{ item.available.quantityRemaining }} 件</text><button aria-label="减少售后数量" size="mini" :disabled="busy || !!frozen || item.quantity===0" @click="change(item,-1)">−</button><text>{{ item.quantity }}</text><button aria-label="增加售后数量" size="mini" :disabled="busy || !!frozen || item.quantity>=item.available.quantityRemaining" @click="change(item,1)">＋</button></view><text v-else class="muted">{{ item.available.unavailableReason || '暂无可申请数量' }}</text><text class="muted">剩余商品现金 {{ amount(item.available.cashRemainingCents) }} · 积分抵扣 {{ amount(item.available.pointRemainingCents) }}</text></view>
<picker :range="types.map(x=>x.label)" :value="typeIndex" :disabled="busy || !!frozen" @change="selectType"><view class="field">售后类型 <b>{{ types[typeIndex]?.label }} ›</b></view></picker><view class="field"><text>售后原因</text><input v-model="reason" :disabled="busy || !!frozen" maxlength="200" placeholder="请说明具体原因"/></view><textarea v-model="description" :disabled="busy || !!frozen" class="textarea" maxlength="2000" placeholder="补充问题描述（选填）"/>
<ImageEvidencePicker :key="loadedSession" v-model="evidenceIds" :locked="busy || !!frozen" @blocked="evidenceBlocked=$event"/><view v-if="quote" class="summary"><view>现金商品退款 <b>{{ amount(quote.merchandiseRefundCents) }}</b></view><view>运费退款 <b>{{ amount(quote.shippingRefundCents) }}</b></view><view>积分返还（抵扣金额） <b>{{ amount(quote.pointReturnCents) }}</b></view><view>现金退款合计 <b>{{ amount(quote.requestedCents) }}</b></view></view><view class="muted note">部分退款默认不退运费。积分在现金退款确认成功后返还；纯积分商品经售后审核后返还，不发起零元渠道退款。换货不退款或返积分。</view><button class="primary-btn" :disabled="busy || quoting || (!frozen && (evidenceBlocked || !quote || !reason.trim()))" @click="submit">{{ busy?'正在处理…':frozen?'按原申请重试':'确认提交申请' }}</button></template><view v-else-if="!error">正在加载订单…</view><button class="outline-btn" @click="viewOrder">查看订单售后进度</button></view></view></template>
<script setup lang="ts">
import { onLoad,onShow,onHide,onUnload } from '@dcloudio/uni-app';import { ref } from 'vue';import DesktopHeader from '../../components/DesktopHeader.vue';import { api,money,toast,requireLogin,mallSessionStamp } from '../../api';
import { mallStorage } from '../../realm';
import ImageEvidencePicker from '../../components/ImageEvidencePicker.vue';
import { validEvidenceIds } from '../../after-sale-images';
const evidenceIds=ref<string[]>([]),evidenceBlocked=ref(false);
const types=[{label:'仅退款',value:'REFUND_ONLY'},{label:'退货退款',value:'RETURN_REFUND'},{label:'换货',value:'EXCHANGE'}];
const id=ref(''),order=ref<any>(),lines=ref<any[]>([]),typeIndex=ref(0),quote=ref<any>(),reason=ref(''),description=ref(''),busy=ref(false),quoting=ref(false),error=ref(''),frozen=ref<any>(null);let revision=0,screen=0,visible=true,loadedSession='';
onLoad(o=>{id.value=String(o?.orderId||'');});onShow(()=>{visible=true;void load();});onHide(invalidate);onUnload(invalidate);
function invalidate(){visible=false;screen++;revision++;order.value=null;lines.value=[];quote.value=null;frozen.value=null;reason.value='';description.value='';evidenceIds.value=[];evidenceBlocked.value=false;busy.value=false;quoting.value=false;loadedSession='';}
function current(version:number,session:string){return visible && version===screen && session===mallSessionStamp();}
async function load(){const version=++screen,session=mallSessionStamp();revision++;order.value=null;lines.value=[];quote.value=null;frozen.value=null;reason.value='';description.value='';evidenceIds.value=[];evidenceBlocked.value=false;busy.value=false;quoting.value=false;error.value='';loadedSession='';
  if(!requireLogin('/pages/after-sale/index?orderId='+encodeURIComponent(id.value)))return;
  try{const value:any=await api('/storefront/orders/'+encodeURIComponent(id.value),{auth:true,sessionStamp:session});if(!current(version,session))return;order.value=value;loadedSession=session;
    const allowed=!value.readOnly && value.allowedActions?.includes('APPLY_AFTER_SALE');lines.value=(value.items||[]).map((item:any)=>({...item,quantity:0,available:allowed?(value.afterSaleEligibleItems?.find((x:any)=>x.orderItemId===item.id)||{quantityRemaining:0}):{quantityRemaining:0,unavailableReason:value.unavailableReason||'当前订单不可申请售后'}}));
    restoreDraft();
  }catch(e){if(current(version,session))error.value=e instanceof Error?e.message:String(e);}}
const input=()=>({type:types[typeIndex.value]!.value,items:lines.value.filter(x=>x.quantity>0).map(x=>({orderItemId:x.id,quantity:x.quantity}))});
function change(item:any,amount:number){if(busy.value||frozen.value)return;item.quantity=Math.max(0,Math.min(item.available.quantityRemaining,item.quantity+amount));void preview();}
function selectType(event:any){if(busy.value||frozen.value)return;const index=Number(event.detail.value);if(!types[index])return;typeIndex.value=index;void preview();}
async function preview(){const request=++revision,version=screen,session=loadedSession;quote.value=null;error.value='';if(!current(version,session)||!input().items.length)return;quoting.value=true;try{const result=await api('/storefront/orders/'+encodeURIComponent(id.value)+'/after-sales/preview',{method:'POST',auth:true,data:input(),sessionStamp:session});if(current(version,session)&&request===revision)quote.value=result;}catch(e){if(current(version,session)&&request===revision)error.value=e instanceof Error?e.message:String(e);}finally{if(current(version,session)&&request===revision)quoting.value=false;}}
const quoteValue=(value:any)=>JSON.stringify([value?.orderVersion,value?.type,value?.requestedCents,value?.merchandiseRefundCents,value?.shippingRefundCents,value?.pointReturnCents,value?.items]);
async function submit(){if(busy.value||quoting.value||(!frozen.value&&(evidenceBlocked.value||!validEvidenceIds(evidenceIds.value)||!quote.value||!reason.value.trim())))return;const version=screen,session=loadedSession;if(!current(version,session))return;busy.value=true;
  try{restoreDraft();if(!frozen.value){const displayed=quoteValue(quote.value);await preview();if(!current(version,session))return;restoreDraft();if(!frozen.value){if(!quote.value)return;if(displayed!==quoteValue(quote.value)){error.value='订单或可退金额已更新，请核对后再次提交。';return;}
      if(evidenceBlocked.value||!validEvidenceIds(evidenceIds.value))return;frozen.value={...input(),orderVersion:quote.value.orderVersion,requestedCents:quote.value.requestedCents,reason:reason.value.trim(),description:description.value,evidenceFileIds:[...evidenceIds.value],idempotencyKey:'h5-after-sale-'+Date.now()+'-'+Math.random().toString(36).slice(2)};saveDraft(frozen.value);}}
    await api('/storefront/orders/'+encodeURIComponent(id.value)+'/after-sales',{method:'POST',auth:true,data:frozen.value,sessionStamp:session});if(current(version,session)){saveDraft(null);viewOrder();}
  }catch(e){if(current(version,session)){if([400,403,404,409,422].includes((e as any)?.status)){saveDraft(null);frozen.value=null;quote.value=null;error.value=(e instanceof Error?e.message:String(e))+'；请刷新剩余额度，并先核对订单售后记录。';}else error.value='申请结果待确认，请先查看订单售后进度；重试会保留原申请内容。';toast(e);}}
  finally{if(current(version,session))busy.value=false;}}
function viewOrder(){uni.redirectTo({url:'/pages/order-detail/index?id='+encodeURIComponent(id.value)});}
function restoreDraft(){const saved=mallStorage.get('after-sale-drafts'),payload=saved?.userId===mallStorage.get('saidian-user')?.id?saved?.orders?.[id.value]:null;if(!payload?.idempotencyKey)return;frozen.value=payload;evidenceIds.value=validEvidenceIds(payload.evidenceFileIds)?[...payload.evidenceFileIds]:[];typeIndex.value=Math.max(0,types.findIndex(x=>x.value===payload.type));reason.value=payload.reason||'';description.value=payload.description||'';for(const line of lines.value)line.quantity=payload.items?.find((x:any)=>x.orderItemId===line.id)?.quantity||0;error.value='上次申请结果待确认，请查看订单售后进度或按原申请重试。';}
function saveDraft(payload:any){const userId=mallStorage.get('saidian-user')?.id,saved=mallStorage.get('after-sale-drafts');const orders=saved?.userId===userId?{...saved.orders}:{};if(payload)orders[id.value]=payload;else if(orders[id.value]?.idempotencyKey===frozen.value?.idempotencyKey)delete orders[id.value];mallStorage.set('after-sale-drafts',{userId,orders});}
function amount(value:unknown){return Number.isSafeInteger(value)?money(value as number):'未获取';}
</script>
<style scoped>.quantity button{min-width:44px;min-height:44px;line-height:44px;padding:0;flex:none}.form .outline-btn{margin-top:12px;min-height:44px}.item,.notice{overflow-wrap:anywhere}</style>
<style scoped>.form{max-width:760px}.form h2{margin:0 0 20px}.muted{font-size:14px;line-height:1.7}.item{padding:20px 0;border-bottom:1px solid var(--line)}.quantity{display:flex;align-items:center;gap:12px;margin-top:12px;font-size:14px}.quantity button{margin:0}.quantity>text:first-child{flex:1}.field{display:flex;align-items:center;justify-content:space-between;gap:20px;min-height:60px;border-bottom:1px solid var(--line);font-size:15px}.field input{flex:1;text-align:right}.textarea{margin-top:18px}.summary{padding:16px;background:#f4f8fc;margin-top:20px}.summary view{display:flex;justify-content:space-between;margin:12px 0;font-size:15px}.note{margin:20px 0}.notice{color:#a82435;padding:12px;background:#fff4f5;margin:12px 0}</style>
