// Hand-reviewed semantics. Route, method, auth and parameter locations come from TS decorators.
const entry = (summary, request = "无请求体", response = "对象", dependency = "核心服务") => ({ summary, request, response, dependency });
const formProfile = "Profile：nickname、head_portrait/avatarUrl、sex/gender、birthday、height/heightCm、weight/weightKg；仅提交需修改字段";
const healthQuery = "date/day=YYYY-MM-DD 或时间戳；selectmember/selectMemberId=被关爱人的数字 ID（缺省自己）；page 从 1 开始；type 见调用手册";
const composition = "JSON {data:{date?,...指标标量}}；建议提供采集时间和 Idempotency-Key；无二者不能保证重试去重";
const push = "PushInstallation：installationId、platform、registrationId、appVersion、buildNumber；字段别名见调用手册";
const address = "Address：name/realname、mobile、province/city/district、detail/address_details、isDefault/is_default；旧地区码字段见调用手册";
const order = "Order：addressId/address_id、items:[{skuId/sku_id,quantity/num}]；旧单品可用 data=JSON 字符串；每次新购买使用新的 Idempotency-Key";
const mall = "主库商城；支付操作还依赖已验收的支付渠道配置";
const category = "{name,parentId?,sort?,enabled?}；parentId 使用分类 UUID";
const article = "{title,contentHtml,summary?,coverUrl?,categoryId?,status?:DRAFT/PUBLISHED/ARCHIVED,publishedAt?}；categoryId 为 UUID";
const legal = "{documentType,version,title,contentHtml,active,publishedAt?}；同类型仅一个激活版本";
const healthBatch = "HealthBatch：JSON {records:[...]}，1–200 条；Idempotency-Key 8–160 字符必填；source可选origin/measurementSource/rawVersion原样独立存储，不填不推断；详细记录结构见调用手册";
const batchResult = "{acceptedIds,rejected:[{id,code,message}],nextCursor}；HTTP 成功不代表全部记录接收";
export const notes = {
  "AdminHealthReportsController.availability": entry("检查会员AI健康报告生成条件", "memberId=国际会员UUID；限SUPER_ADMIN/HEALTH_AUDITOR", "{canGenerate,reasons:[{code,message}],period,validRecordCount,distinctDays,minimumDistinctDays,consentRequired,memberConsentBypass,availableCredits,latestReport}；SUPER_ADMIN后台生成不以会员App同意为前置，HEALTH_AUDITOR仍须当前同意；未知条件不伪装可用；不返回密钥，不探测外部服务", "有效数据、报告次数、已配置AI和未暂停Worker；审核员另需会员当前同意"),
  "AdminHealthReportsController.create": entry("后台申请生成或复用AI健康报告", "{memberId:UUID,idempotencyKey:8–160字符}；不创建付款；每次请求服务端复核条件", "{report:{id,status,period,dataCompleteness,freePreview,aiGenerated,aiLabel,generatedAt,createdAt,needsPayment},reused}；SUPER_ADMIN可绕过会员App同意且审计memberConsentBypassed=true，HEALTH_AUDITOR不可绕过；状态小写；会员级锁与同事务报告/扣次/Outbox/审计；同会员同键重放，失败409 health_report_unavailable", "已满足availability条件；第三方真实运行需独立验收"),
  "AdminHealthReportsController.detail": entry("后台查看健康报告进度和结果", "id=国际健康报告UUID；限SUPER_ADMIN/HEALTH_AUDITOR", "报告结构+memberId；READY加content:{overview,trends:[{metric,text}],suggestions,limitations}和limitations；FAILED仅安全提示；返回前强制HEALTH_REPORT_READ审计，未完成不返回正文", "报告队列与读取审计；AI结果仅供健康管理参考"),
  "AdminHealthReportsController.update": entry("超级管理员复核并编辑已生成健康报告", "id=报告UUID；仅SUPER_ADMIN；{content:{overview,trends:[{metric,text}],suggestions,limitations},expectedUpdatedAt}；指标、顺序和证据ID不可修改", "更新后的报告正文；使用乐观锁，版本冲突返回409；HEALTH_REPORT_UPDATE审计只保存内容散列和变更章节，不保存报告正文", "已生成READY报告；内容仅供日常健康管理参考"),
  "AdminController.commerceFulfillmentPreview": entry("本地订单可发货数量", "订单UUID路径参数；限超级管理员/商城运营", "{orderId,version,status,items:[{orderItemId,name,quantity,shippedQuantity,refundedQuantity,afterSaleReservedQuantity,remainingQuantity}],shipments,unavailableReason?}；旧包裹或售后归属不明时阻断", mall),
  "AdminController.createCommerceShipment": entry("登记本地商品分包发货", "{version,logisticsCompany,trackingNo,items:[{orderItemId,quantity}]}；仅已接管的新LOCAL已付款订单；运单号3–100位字母数字._-", "发货预览结构及shipmentId/replayed；同订单同运单同内容重试幂等，异参/超量/过期版本409；不生成承运轨迹", mall),
  "AdminController.currentAdmin": entry("当前后台身份和多角色", undefined, "{id,role,roles}；服务端每次请求检查实时角色，前端菜单仅权限提示"),
  "AdminController.saveCommerceCommissionPlan": entry("保存佣金及提现规则", "{enabled,rateBps,settlementDays,withdrawalEnabled,minimumWithdrawCents,dailyWithdrawLimitCents,reviewRequired:true}；新规则不追改已计提快照", "佣金计划与提现规则", "财务人工审批"),
  "CommerceEmployeeWithdrawalController.summary": entry("员工提现账户与申请记录", undefined, "{wallet,identity,plan,pendingCount,canApply,payoutMode,withdrawals}；未知余额为null", "已核验收款身份和提现规则"),
  "CommerceEmployeeWithdrawalController.apply": entry("申请提现并冻结可用余额", "{amountCents:正整数分,idempotencyKey}；校验最低额、北京自然日额度、欠款及同员工一条在途", "提现记录；不调用打款供应商", "已启用提现规则和核验身份"),
  "CommerceAdminWithdrawalController.list": entry("提现审核分页列表", "page/pageSize/status", "{items,total,page,pageSize}；收款标识脱敏", "主库资金账本"),
  "CommerceAdminWithdrawalController.review": entry("审批提现申请", "{version,idempotencyKey,decision:APPROVE/REJECT,note}；拒绝同事务释放冻结", "提现记录；重复同键幂等，异参或旧版本409", "主库资金账本"),
  "CommerceAdminWithdrawalController.receipt": entry("登记真实人工转账回执", "{version,idempotencyKey,providerTransferId,amountCents,recipientOpenId,receiptReference,evidence,completedAt,confirmedExternalResult:true}；核验金额及收款身份", "提现记录；仅登记已完成的真实转账，不发起任何第三方付款", "财务人工核验凭证"),
  "CommerceAdminWithdrawalController.verify": entry("核验迁入在途原转账结果", "回执字段同manual-receipt，另result=SUCCEEDED/FAILED；必须原转账号一致、已接管且PROCESSING/WAIT_USER_CONFIRM", "成功结账或失败释放冻结；不得创建新转账单", "原渠道回执"),
  "AdminController.batchCommerceProducts": entry("商品批量上下架与归档", "{ids:商品UUID数组,action:PUBLISH/DISABLE/ARCHIVE}；ERP和自建商品保留各自库存权威", "批量处理结果", mall),
  "LegacyCartController.index": entry("旧App购物车列表", undefined, "数组：整数id/cart_item_id/sku_id/product_id、num/quantity、元单位price、available", mall),
  "LegacyCartController.create": entry("旧App加入购物车", "multipart sku_id、num正整数；同会员SKU原子累加", "剩余购物车旧结构数组", mall),
  "LegacyCartController.updateNumber": entry("旧App修改购物车数量", "multipart sku_id、num正整数；只更新当前会员已存在项", "购物车旧结构数组", mall),
  "LegacyCartController.deleteIds": entry("旧App批量删除购物车", "multipart sku_ids=SKU整数ID逗号串；限定当前会员", "剩余购物车旧结构数组", mall),
  "LegacyMemberController.warningSettings": entry("旧App预警开关与阈值", undefined, "heart_auto/heart_num/blood_pressure_auto/blood_glucose_auto/body_temperature_auto；不提供诊断"),
  "LegacyMemberController.saveWarningSettings": entry("保存旧App预警配置", "multipart旧开关与heart_num；保留未暴露的阈值和共享配置；未配置阈值不得开启", "旧预警配置"),
  "LegacyMemberController.feedback": entry("旧App意见反馈", "multipart type/content/contact/attachments；附件需本人所有", "{id,status}"),
  "LegacySiteController.version": entry("旧App正式版本更新", "platform=android|ios；v=当前构建号", "version/version_code/lowwer/force/status/android_type/android|ios/sha256；无新版null；未配置404、坏配置503", "后台legacy_app_update正式发布配置"),
  "BillingAdminController.replayProviderEvents": entry("回放已验签支付回调", "{limit?:1–100}；先解除回调处理暂停；只回放已持久化且verifiedAt不空的事件", "{items:[{id,processed,error?}],remaining}；失败不算完成", "支付回调Inbox"),
  "StatusController.live": entry("进程存活", undefined, "{status,service,revision}"),
  "StatusController.ready": entry("数据库就绪", undefined, "{status,database,revision}；失败 HTTP 503；不证明供应商可用"),
  "AuthController.register": entry("账号注册", "国内环境仍阻止裸密码注册；国际环境仅在GLOBAL_UNVERIFIED_REGISTRATION_ENABLED=true时接受{channel,identifier,password,nickname?,consentVersion,locale?}", "国际环境签发Session，但联系方式保持未验证；关闭临时开关后未验证会话不可续期", "国际独立数据库、已审协议与显式临时开关；需验证联系方式的商城能力仍阻断"),
  "AuthController.capabilities": entry("国际账号可用能力", "locale可选；仅APP_REALM=global", "{realm,defaultLocale,supportedLocales,registration:{email,sms,verificationRequired},recovery:{email,sms},smsCountries,verification,consentVersion,legal}；verificationRequired=false只表示当前注册暂免验证码；recovery仍要求已验收渠道且不在写入维护期", "国际独立数据库、已审协议及显式注册开关"),
  "AuthController.verificationCode": entry("国际邮箱/手机号验证码", "{channel:email|sms,identifier,purpose:register|reset_password,locale?}；sms必须E.164", "{challengeId,expiresIn:300,retryAfter:60,maskedIdentifier}；不返回验证码", "独立email_otp/sms_global webhook"),
  "AuthController.registerWithCode": entry("国际已验证账号注册", "{challengeId,code,password,nickname?,consentVersion,locale?}；consentVersion必须来自当前已审协议", "Session；国际UUID账号，与国内账号不互通", "已送达未消费的国际验证码与已发布协议"),
  "AuthController.login": entry("密码登录", "国内{mobile/username,password}；国际{channel:email|sms,identifier,password}", "Session；国际member含emailMasked/phoneMasked/locale可选字段"),
  "AuthController.wechatLogin": entry("原生微信授权登录", "{code,state,platform:android/ios/harmony,consentAccepted:true,consentVersion}；只提交一次性 code，密钥仅在服务端", "Session；手机号仍未验证时不得映射商城身份", "微信开放平台移动应用"),
  "AuthController.requestSms": entry("发送验证码", "{mobile,usage:register/reset_password}", "发送状态；不返回验证码", "短信供应商"),
  "AuthController.registerWithSms": entry("短信注册", "{mobile,code,password,nickname?,consentVersion}", "Session", "短信供应商"),
  "AuthController.resetPassword": entry("验证码重置密码", "国内{mobile,code,password/newPassword}；国际{challengeId,code,password}", "Session；旧会话失效", "对应部署的验证码供应商"),
  "AuthController.refresh": entry("轮换刷新令牌", "{refreshToken}；客户端必须串行刷新并替换旧令牌", "Session"),
  "AuthController.logout": entry("退出当前会话", undefined, "{loggedOut:true}"),
  "AuthController.deleteAccount": entry("提交账号注销申请", undefined, "注销任务；并非立即删除全部数据"),
  "MembersController.profile": entry("本人资料", undefined, "Profile；id仍为UUID；国际版memberNo为稳定数字展示编号，promo_code是现有App我的页面的同值展示别名，不用于鉴权或推广归属"),
  "MembersController.saveProfile": entry("修改本人资料", formProfile, "Profile"),
  "MembersController.goals": entry("活动目标", undefined, "{steps,distanceMeters,caloriesKcal}；未知为 null"),
  "MembersController.saveGoals": entry("保存活动目标", "{steps,distanceMeters,caloriesKcal}；缺省字段置 null，客户端应提交完整目标", "活动目标"),
  "HealthController.ingestBatch": entry("健康批量同步", healthBatch, batchResult),
  "HealthController.list": entry("本人健康历史", "metric=规范指标；limit 正整数默认50最大200；before=上页nextCursor（不透明复合游标）；继续接受旧ISO时间", "{items,nextCursor}；按采集时间和UUID稳定分页，相同采集时间记录不丢页"),
  "HealthController.warningRules": entry("读取阈值提醒", undefined, "规则数组；未获取阈值为 null"),
  "HealthController.warnings": entry("读取提醒事件", "limit 默认 50", "提醒数组；仅阈值提醒，不是诊断"),
  "HealthController.saveWarningRules": entry("保存阈值提醒", "{rules:[{metric,enabled,lowThreshold?,highThreshold?,secondaryHighThreshold?,shareWithCare?}]}；目前仅本人的提醒闭环", "保存后的规则数组"),
  "HealthReportsController.profile": entry("会员健康档案", "无请求体；默认汇总近30天有效记录", "健康数据完整度、指标摘要、设备、预警数和分析同意状态；国际analysisConsent含availableVersion/document，均可为null"),
  "HealthReportsController.setAnalysisConsent": entry("设置健康AI分析单独同意", "{granted:boolean,version:string,locale?}；国际version必须匹配当前已审health_ai_analysis文档；撤回时granted=false", "同意或撤回状态；缺文档不授予，撤回后不能新生成AI报告"),
  "HealthReportsController.eligibility": entry("检查详细报告生成条件", "无请求体；默认近30天", "至少3个自然日的有效记录、缺失说明、可用次数和同意要求"),
  "HealthReportsController.list": entry("健康报告历史", "无请求体", "本人最多100份报告；已生成报告可重复查看"),
  "HealthReportsController.create": entry("创建健康报告请求", "无请求体；数据不足时不创建支付单", "报告预览及needsPayment；有次数时进入队列"),
  "HealthReportsController.get": entry("健康报告状态与免费概览", "id=报告UUID", "报告状态、数据区间和免费概览；不含付费正文"),
  "HealthReportsController.full": entry("查看已解锁详细健康报告", "id=报告UUID", "AI标识、证据索引、局限及详细内容；非诊断"),
  "HealthReportsController.export": entry("按需导出详细健康报告", "id=已解锁且生成完成的报告UUID", "application/pdf文件流；不长期重复保存PDF", "报告字体服务"),
  "HealthReportsController.retry": entry("重试失败的报告", "id=报告UUID；国际必须仍同意当前已审health_ai_analysis版本", "重新排队后的报告；撤回授权/文档未发布/版本过期拒绝入队；生成失败时次数已返还", "AI供应商"),
  "DevicesController.list": entry("已绑定设备", undefined, "Device[]；只含未解绑设备"),
  "DevicesController.bind": entry("绑定设备快照", "{deviceId/hardwareId,vendor,model,displayName/name,firmware?,capabilities?:string[],syncCursor?}", "Device；不是服务端蓝牙连接"),
  "DevicesController.updateCapabilities": entry("更新设备能力及游标", "{capabilities:string[],firmware?,syncCursor?}；id=绑定记录 UUID", "Device"),
  "DevicesController.unbind": entry("解绑设备", "id=绑定记录 UUID", "{unbound:true}；保留历史健康数据"),
  "CareController.relationships": entry("关爱关系列表", undefined, "CareRelationship[]，含 direction、双方昵称、授权指标"),
  "CareController.invite": entry("邀请查看对方健康数据", "国内{mobile}；国际{identifier:email/E.164}；仅同部署账号域；不能自邀；已生效返回 409", "CareRelationship；UUID；逐指标授权不变"),
  "CareController.respond": entry("接受或拒绝邀请", "id=关系 UUID；{accepted:boolean}；仅收件人可操作", "CareRelationship；接受后仍需逐指标授权"),
  "CareController.savePermissions": entry("共享本人指标", "id=关系 UUID；{metrics:规范指标数组,expiresAt?:ISO8601}；仅数据所属人；[] 撤销全部指标", "CareRelationship"),
  "CareController.revoke": entry("撤销关爱关系", "id=关系 UUID；任一参与方可撤销", "CareRelationship；撤销后不能查询"),
  "CareController.preview": entry("按授权查看健康数据", "id=关系 UUID；metric 必填；from/to=ISO8601；缺省近 7 天；左闭右开", "HealthRecord[]；逐指标授权并记录审计，拒绝 403"),
  "NotificationsController.list": entry("消息列表", "page 默认 1；pageSize 默认 30", "分页消息"),
  "NotificationsController.unread": entry("未读数", undefined, "{count}"),
  "NotificationsController.preferences": entry("读取通知偏好", undefined, "{transactionalEnabled,marketingEnabled,updatedAt}；营销通知默认关闭"),
  "NotificationsController.updatePreferences": entry("修改通知偏好", "{transactionalEnabled?,marketingEnabled?}；至少提交一项", "保存后的通知偏好；业务必要通知与营销通知分开"),
  "NotificationsController.detail": entry("消息详情", "id=消息 UUID", "Notification；V2 GET 不标记已读"),
  "NotificationsController.markRead": entry("标记消息已读", "id=消息 UUID/eventId", "{read:true}；仅本人消息"),
  "NotificationsController.register": entry("登记推送安装", push, "安装记录；登记不等于推送成功", "推送供应商（登记可独立使用）"),
  "NotificationsController.unregister": entry("撤销本人推送安装", "installationId=安装标识", "撤销结果"),
  "ContentController.categories": entry("文章分类", "parentId 可选 UUID；缺省顶级；国际按locale/Accept-Language精确匹配，默认en", "ArticleCategory[]；未翻译不返回其他语言替代"),
  "ContentController.articles": entry("已发布文章", "categoryId 可选 UUID；page 默认 1；pageSize 默认 20 最大 50；国际locale/Accept-Language", "{items,total,page,pageSize}；国际仅已发布的对应语言"),
  "ContentController.article": entry("文章详情", "id=UUID 或迁移的旧文章 ID；国际locale/Accept-Language", "Article；未发布/未来发布/国际语言不匹配 404"),
  "ContentController.legal": entry("协议文档", "type=文档类型；version可选；国际locale必选当前capabilities法律文档locale", "国内LegalDocument；国际GlobalLegalDocument（reviewed+active+published）；未发布404"),
  "AiController.history": entry("本人 AI 历史", "sessionId 可选客户端会话标识", "最近 20 个会话及消息"),
  "AiController.send": entry("AI 提问", "{content/message,sessionId?,locale?}；正文 1–4000 字符；国际8语默认使用会话/账号语言或en", "{id,conversationId,role,content,createdAt}", "AI 供应商；未配置返回 503；语言指令不改变健康安全边界"),
  "SupportController.config": entry("客服配置", undefined, "客服配置或未配置状态"),
  "SupportController.appUpdate": entry("App 下载与更新配置", undefined, "DownloadManifest v1；Android/iPhone/HarmonyOS 各一项，待开放项无下载地址；国际仅global_app_update，强制realm=global及逐项独立packageId，直包仅/global/down/files/；无配置404"),
  "SupportController.feedback": entry("提交反馈", "{content:5–2000字符,category?,contact?:最多100字符,attachments?:本人文件ID数组最多6项}", "{id,status}"),
  "FilesController.upload": entry("上传图片", "multipart file；purpose=avatar/feedback；最大 10 MiB；JPEG/PNG/WebP", "{id,url,...}", "私有对象存储"),
  "FilesController.uploadEcg": entry("上传 ECG 压缩文件", "multipart file + sha256；最大 25 MiB；gzip；先上传再提交 HealthBatch 引用", "ECG 对象键和摘要；原始波形非公开", "私有对象存储"),
  "FilesController.download": entry("获取公开头像", "id=文件 UUID；仅 ACTIVE 且 purpose=avatar 的文件", "原始文件流，不包裹 JSON；反馈/ECG 不可经此接口下载", "对象存储"),
  "CommerceController.home": entry("商城首页", undefined, "主库商城首页数据", mall),
  "CommerceController.markets": entry("国际市场可用状态", undefined, "{markets:[{countryCode,currency,currencyExponent,commerceEnabled,paymentChannels:[]}]}；未配置默认为CN/CNY且commerceEnabled=true；显式停用保留", "global.markets；仅CN收货/CNY整数分价目可结算；其他币种只读元数据；支付可用性另查capabilities"),
  "CommerceController.products": entry("商城商品列表", "page、pageSize、keyword、categoryId、sort", "主库商品分页", mall),
  "CommerceController.product": entry("商城商品详情", "id=商品UUID", "主库商品及SKU", mall),
  "CommerceController.cart": entry("购物车", undefined, "本人主库购物车", mall),
  "CommerceController.putCart": entry("更新购物车项", "{skuId,quantity,selected?}", "本人主库购物车", mall),
  "CommerceController.deleteCart": entry("删除购物车项", "id=购物车项UUID", "删除结果", mall),
  "CommerceController.addresses": entry("地址列表", undefined, "Address[]", mall),
  "CommerceController.address": entry("地址详情", "id=商城地址 ID", "Address", mall),
  "CommerceController.saveAddress": entry("新增地址", address, "Address", mall),
  "CommerceController.updateAddress": entry("更新地址", address, "Address", mall),
  "CommerceController.deleteAddress": entry("删除地址", "id=商城地址 ID", "{deleted:true}", mall),
  "CommerceController.orders": entry("当前订单与历史投影", "status=商城订单枚举；或group=pending_shipment|after_sales，互斥可选", "Order[]；按服务端完整数据筛选，待发货含已付款，售后包含已处理记录；历史投影只读", mall),
  "CommerceController.order": entry("订单详情", "id=主库订单UUID或旧投影ID", "Order", mall),
  "CommerceController.createOrder": entry("多商品创建单个商城订单", order + "；expectedQuote可选，取preview.quote.fingerprint", "Order；报价变化409 quote_changed且无资产写入，同键原参已创建优先返回原订单；global仅CN收货且currency=CNY", mall),
  "CommerceController.previewOrder": entry("预览商城订单", order, "收货地址、商品和服务端金额及quote.fingerprint；不创建订单；global非CN地址400 delivery_country_unsupported，已停用市场503 market_checkout_unavailable", mall),
  "CommerceController.receipt": entry("确认收货", "id=主库订单UUID", "{received:true}；旧订单拒绝409", mall),
  "CommerceController.cancel": entry("取消待付款订单", "id=商城订单UUID", "取消结果并恢复本地库存占用；旧订单拒绝409", mall),
  "CommerceController.afterSales": entry("申请售后", "id=主库订单UUID；{type,reason,requestedCents?,description?,evidenceFileIds?:UUID[],evidenceImages?,idempotencyKey?}；新图片先上传，最多9个不同本人文件ID；global禁非空外部evidenceImages", "主库售后记录，图片引用为file:UUID；旧订单拒绝409；同键原完整请求恢复，不重传或更换图片ID", mall),
  "CommerceController.logistics": entry("订单物流", "id=主库订单UUID", "物流轨迹数组", mall),
  "CommerceController.payment": entry("生成 App 支付参数", "{orderId,channel:wechat_app/alipay_app}；金额以商城订单为准；幂等头透传", "{paymentNo,channel,invoke}；不等于付款成功", mall),
  "CommerceController.favorites": entry("收藏商品列表", "无请求体", "当前可售商品卡片数组", "主库商城"),
  "CommerceController.favorite": entry("收藏或取消收藏", "id=商品UUID；{enabled:boolean}", "保存结果", "主库商城"),
  "CommerceController.coupons": entry("本人优惠券", "无请求体", "优惠券领取与使用状态", "主库商城"),
  "CommerceController.claimCoupon": entry("领取优惠券", "id=优惠券UUID", "领取记录；重复领取幂等", "主库商城"),
  "CommerceController.review": entry("评价已收货商品", "{orderItemId,rating,content,images?}", "评价记录", "主库商城"),
  "BillingController.offers": entry("健康报告购买方案", "platform=android/ios/h5/mini_program/web，可选", "后台启用且当前有效的版本化价格方案"),
  "BillingController.entitlements": entry("健康报告权益", "无请求体", "可用次数及30天会员到期时间"),
  "BillingController.createPayment": entry("创建统一支付单", "{businessType,businessId,offerId?,channel,platform,idempotencyKey}；金额和权益由服务端确定", "PaymentIntent及渠道调用参数；不等于付款成功；global仅CNY商城订单的wechat_jsapi/wechat_h5/wechat_native/alipay_wap/alipay_page；StoreKit沿用原规则", "未配置或出站暂停返回503；global其他业务/币种/原生App或小程序支付503 payment_unavailable，创建资金关系前拒绝；同键同单已有支付优先返回"),
  "BillingController.payment": entry("查询支付结果", "id=PaymentIntent UUID", "本人支付状态；客户端应以服务端状态为准"),
  "BillingController.verifyApple": entry("验证StoreKit交易", "{paymentIntentId,signedTransactionInfo}", "验证成功后的支付与权益", "Apple App Store Server；未配置返回503"),
  "BillingController.appleNotification": entry("接收App Store Server Notifications V2", "{signedPayload}；外层和内层JWS均须通过Apple证书链验证", "{received:true}；退款或撤销会收回对应报告权益", "Apple App Store Server"),
  "BillingController.wechatRefundNotify": entry("微信退款结果回调", "微信支付API v3加密通知；必须校验平台签名并解密", "SUCCESS确认；处理中、关闭或异常不伪报退款成功", "微信支付"),
  "BillingAdminController.refundAfterSale": entry("按已审核售后发起退款", "id=售后UUID；{reason?}；退款金额由售后单确定", "退款记录；渠道受理不等于成功，最终以验签回调或已验签同步结果为准", "微信支付/支付宝"),
  "BillingAdminController.createRefund": entry("财务发起指定支付退款", "id=支付UUID；{amountCents,reason,afterSaleId?,idempotencyKey}；金额单位分", "幂等退款记录；Apple购买退款需由App Store处理", "微信支付/支付宝"),
  "BillingController.wechatNotify": entry("微信支付验签通知", "微信支付V3原始JSON及Wechatpay签名头", "微信要求的SUCCESS响应；事件幂等", "微信支付V3"),
  "BillingController.alipayNotify": entry("支付宝验签通知", "支付宝form通知字段", "支付宝要求的success文本；事件幂等", "支付宝开放平台"),
  "LegacySiteController.login": entry("旧版密码登录", "表单 username/mobile、password", "LegacySession"),
  "LegacySiteController.wechatLogin": entry("旧版 App 原生微信授权登录", "表单 code、state、platform=android/ios/harmony、group=app、consent_accepted=1、consent_version；不接收 AppSecret", "LegacySession", "微信开放平台移动应用"),
  "LegacySiteController.register": entry("旧版注册", "表单 mobile/username、password、nickname?、consent_version?、code?；无 code 路径的上线限制见缺陷清单", "LegacySession"),
  "LegacySiteController.smsCode": entry("旧版短信验证码", "表单 mobile、usage=register/reset/forgot/up-pwd/reset_password", "发送状态", "短信供应商"),
  "LegacySiteController.resetPassword": entry("旧版重置密码", "表单 mobile、code、password", "LegacySession", "短信供应商"),
  "LegacySiteController.refresh": entry("旧版刷新", "表单 refresh_token", "LegacySession"),
  "LegacySiteController.logout": entry("旧版退出", undefined, "{logged_out:true}"),
  "LegacyMemberController.member": entry("旧版本人资料", undefined, "LegacyProfile：数字 id、uuid、mobile、nickname、head_portrait 等"),
  "LegacyMemberController.saveMember": entry("旧版修改资料", formProfile, "LegacyProfile"),
  "LegacyMemberController.goals": entry("旧版活动目标", undefined, "{steps,juli,reliang}"),
  "LegacyMemberController.saveGoals": entry("旧版保存目标", "表单 steps、juli(米)、reliang(kcal)", "规范目标对象；以重新读取为准"),
  "LegacyMemberController.healthBatch": entry("旧前缀批量健康同步", healthBatch + "；V1 缺少幂等头时使用请求摘要", batchResult),
  "LegacyMemberController.saveActivity": entry("旧版当日活动快照", "{steps_num,reliang_num,juli_num}；无采集日期，仅作接收当日快照，不能回填过去日期", batchResult),
  "LegacyMemberController.saveDaily": entry("旧版日健康同步", "JSON {dailyDate:[{date,heartReat?,pulseReat?,bloodPressure?,bloodOxygen?,...}]}；1–2000 行，展开后分批；见调用手册", batchResult + "；任意拒绝时业务 400，不伪报全部成功"),
  "LegacyMemberController.dailyPreview": entry("旧版健康预览", healthQuery, "LegacyDaily[]；同一小时多条记录保留；最多 20000 条，超出要求缩小范围"),
  "LegacyMemberController.dailyHistory": entry("小程序健康历史列表", healthQuery, "LegacyDaily[]；按 30 条规范记录分页，无日期时查历史"),
  "LegacyMemberController.bloodHistory": entry("小程序血液成分历史", healthQuery, "[{id,date,...指标}]，每页 30 条"),
  "LegacyMemberController.saveBodyComposition": entry("旧版身体成分同步", composition, batchResult),
  "LegacyMemberController.previewBodyComposition": entry("旧版身体成分预览", healthQuery, "[{id,date,...指标}]"),
  "LegacyMemberController.saveBloodComposition": entry("旧版血液成分同步", composition, batchResult),
  "LegacyMemberController.previewBloodComposition": entry("旧版血液成分预览", healthQuery, "[{id,date,...指标}]"),
  "LegacyMemberController.saveEcg": entry("旧版 ECG 同步", "JSON {data:{date,sampleFrequency?,...摘要},totalArray:采样数组}；先压缩存储再写摘要", batchResult, "对象存储"),
  "LegacyMemberController.previewEcg": entry("旧版 ECG 摘要历史", healthQuery, "[{id,date,...摘要,ecgArtifact?}]；波形下载尚未闭环"),
  "LegacyMemberController.bodyDetail": entry("小程序身体成分单条", "id=本人 clientRecordId 或 UUID", "{id,date,...指标}；非本人 404"),
  "LegacyMemberController.careInvitations": entry("旧版关爱关系", undefined, "LegacyCare[]：数字关系及成员 ID、examine_status、setting"),
  "LegacyMemberController.careMembers": entry("旧版已关爱成员", undefined, "本人发出的已生效 LegacyCare[]"),
  "LegacyMemberController.addCare": entry("旧版发出邀请", "{mobile}", "规范 CareRelationship；旧页面随后刷新列表获取数字 ID"),
  "LegacyMemberController.respondCare": entry("旧版处理邀请", "{id:数字关系ID,examine_status:1接受/其他拒绝}", "CareRelationship"),
  "LegacyMemberController.careSettings": entry("旧版读取共享范围", "to_member_id=另一方数字成员 ID", "{setting:JSON字符串}；值使用 heartReat/bloodPressure 等旧拼写"),
  "LegacyMemberController.saveCareSettings": entry("旧版保存共享范围", "{to_member_id,setting:数组或JSON字符串}；仅数据本人可修改；未知指标拒绝", "CareRelationship"),
  "LegacyMemberController.carePreview": entry("旧版关爱汇总", "id=数字关系 ID；date/day 可选", "{daily:LegacyDaily[],jrjk:{steps_num,juli_num,reliang_num}}；未授权指标不返回，未知 null"),
  "LegacyMemberController.notificationList": entry("旧版消息列表", "page 默认 1，每页 30", "LegacyNotification[]"),
  "LegacyMemberController.unread": entry("旧版消息未读数", undefined, "{unread_count}"),
  "LegacyMemberController.notificationStatistics": entry("旧版消息分类未读数", undefined, "{announce_count,remind_count,unread_count}"),
  "LegacyMemberController.notification": entry("旧版消息详情并标已读", "id=数字 ID/UUID/eventId", "LegacyNotification；GET 有兼容副作用，不适合缓存或预取"),
  "LegacyMemberController.readNotification": entry("旧版标记已读", "id=数字 ID/UUID/eventId", "已读结果"),
  "LegacyMemberController.pushDevice": entry("旧版登记推送安装", push, "安装记录", "推送供应商（登记可独立使用）"),
  "LegacyMemberController.removePushDevice": entry("旧版撤销安装", "installationId", "撤销结果"),
  "LegacyMemberController.deleteAccount": entry("旧版提交注销", undefined, "注销任务"),
  "LegacyContentController.categories": entry("旧版文章分类", "pid=旧分类 ID/UUID", "[{id,pid,title,name,sort}]；新增分类数字 ID 兼容缺口见缺陷清单"),
  "LegacyContentController.articles": entry("旧版文章列表", "cate_id=旧分类 ID/UUID；page 默认 1，每页 20", "LegacyArticle[]；新增文章 ID 兼容缺口见缺陷清单"),
  "LegacyContentController.article": entry("旧版文章详情", "id=迁移旧文章 ID/UUID", "LegacyArticle"),
  "LegacyContentController.single": entry("旧版单页文章/协议", "id=原单页文章 ID；当前查询 Article，尚未映射 LegalDocument", "LegacyArticle；协议映射缺口见缺陷清单"),
  "LegacyContentController.aiHistory": entry("旧版 AI 历史", "session_id 可选", "[{id,session_id,role,message,content,created_at}]"),
  "LegacyContentController.sendAi": entry("旧版 AI 提问", "JSON/表单 message、session_id?", "{id,session_id,role,message,content,created_at}", "AI 供应商"),
  "LegacyPagesController.page": entry("旧版商城首页结构", "code 可选", "{code,items}；swiper/tabs 商品结构", mall),
  "LegacyProductController.product": entry("旧版商品详情", "id=首页返回的数字商品 ID", "LegacyProduct（数字 SKU、价格元、库存）", mall),
  "LegacyOrderController.orders": entry("旧版订单列表", "synthesize_status=0待付/1待发/2待收/3完成/4取消/-1售后/-3退款，可选", "LegacyOrder[]；read_only 标明历史订单", mall),
  "LegacyOrderController.order": entry("旧版订单详情", "id=数字订单 ID", "LegacyOrder", mall),
  "LegacyOrderController.preview": entry("旧版下单预览", order + "；GET 查询参数", "{address,products,...金额}", mall),
  "LegacyOrderController.createOrder": entry("旧版创建订单", order, "LegacyOrder；响应不是支付成功", mall),
  "LegacyOrderController.createBatchOrder": entry("旧版多商品单订单", order, "单个 LegacyOrder，非逐商品拆单", mall),
  "LegacyOrderController.receipt": entry("旧版确认收货", "表单 id=数字订单 ID", "确认结果；历史订单拒绝 409", mall),
  "LegacyOrderController.refund": entry("旧版申请售后", "表单 id=数字订单项ID，type、reason 等按商城约定", "售后结果", mall),
  "LegacyOrderController.express": entry("旧版物流详情", "order_id=数字订单ID", "{data:物流轨迹数组}", mall),
  "LegacyAddressController.list": entry("旧版地址列表", undefined, "LegacyAddress[]", mall),
  "LegacyAddressController.detail": entry("旧版地址详情", "id=数字地址 ID", "LegacyAddress", mall),
  "LegacyAddressController.create": entry("旧版新增地址", address, "LegacyAddress", mall),
  "LegacyAddressController.update": entry("旧版更新地址", address, "LegacyAddress", mall),
  "LegacyAddressController.remove": entry("旧版删除地址", "id=数字地址 ID", "删除结果", mall),
  "LegacyPaymentController.create": entry("旧版生成支付参数", "multipart pay_type=1微信/2支付宝（兼容100/101）、trade_type=app、order_group=order、data=JSON字符串含order_id；不相信客户端金额", "{payment_no,channel,config}；订单状态以服务端回查为准", mall),
  "LegacyFilesController.upload": entry("旧版上传头像", "multipart file，JPEG/PNG/WebP，最大 10 MiB", "{id,url,path,...}；path 与 url 相同", "对象存储"),
  "AdminLoginController.login": entry("后台登录", "JSON {username,password}", "AdminSession；不能与 App Token 混用"),
  "AdminController.logout": entry("后台退出", undefined, "{loggedOut:true}"),
  "AdminController.dashboard": entry("运营概览", undefined, "会员/健康/关爱/预警/反馈/积压数量"),
  "AdminController.members": entry("会员查询", "search 查昵称/手机号/旧会员ID/数字memberNo，国际版另支持邮箱；page默认1；pageSize默认30最大100；国际后台直接查询国际新库", "{items,total,page,pageSize}；包含数字memberNo、脱敏手机号，国际版另含emailMasked；使用对应服务的管理员会话与角色权限"),
  "AdminController.memberProfile": entry("超级管理员读取会员编辑资料", "id=会员UUID；仅国际版SUPER_ADMIN", "会员编号、头像、姓名/昵称、性别、出生日期、身高、体重、未脱敏手机号/邮箱、账号状态及独立验证状态；读取写入专门审计，不返回密码和健康记录"),
  "AdminController.updateMemberProfile": entry("超级管理员编辑会员资料", "id=会员UUID；{nickname,avatarUrl?,gender:MALE|FEMALE|UNSPECIFIED,birthday?:YYYY-MM-DD,heightCm?:50..250,weightKg?:10..500,mobile?,email?,status:ACTIVE|DISABLED,mobileVerified,emailVerified,newPassword?:8至72字节,expectedUpdatedAt}；手机号须含国家区号，手机或邮箱至少保留一项", "原子更新 App 基本资料、联系方式验证状态及可选新密码；联系方式、验证、账号状态或密码变化会注销会员现有会话，单独修改基本资料不会；重复联系方式409、过期版本409、注销流程会员409；专门审计只保存变更字段名和密码是否变更，不保存资料值、完整联系方式或密码"),
  "AdminController.updateMemberVerification": entry("超级管理员人工确认联系方式", "id=会员UUID；{channel:mobile|email,verified:boolean,expectedUpdatedAt}；只调整已有联系方式的验证状态，不修改号码或邮箱", "返回脱敏联系方式与手机/邮箱独立验证状态；并发变化409；写入专门审计。人工确认后会员需重新登录，临时测试会话不会原地提权"),
  "AdminController.healthSummary": entry("会员健康数量摘要", "id=会员 UUID", "按指标数量与首末采集时间"),
  "AdminController.rawHealth": entry("授权查看原始健康记录", "id=会员 UUID；reason=5–300字业务原因，国际SUPER_ADMIN可不填（以服务端会话角色为准），HEALTH_AUDITOR和国内接口仍必填；limit 默认100 最大500", "HealthRecord[]；原因、操作者和请求编号进入专门读取审计；国际免填记录SUPER_ADMIN_EXEMPTION，不跳过审计"),
  "AdminController.care": entry("后台关爱关系", undefined, "最多500条，双方昵称和指标权限；尚无分页"),
  "AdminController.devices": entry("后台设备快照", undefined, "最多500条；尚无分页"),
  "AdminController.uploadContentImage": entry("上传后台文章或协议图片", "multipart/form-data字段file；JPG/PNG/WebP，文件签名须匹配，单张不超过10MB；仅SUPER_ADMIN/CONTENT_EDITOR", "{id,url,sha256,byteSize}；url为当前部署公开文件地址，不返回对象存储密钥", "已配置对象存储"),
  "AdminController.feedback": entry("反馈工单", "status=OPEN/IN_PROGRESS/RESOLVED/CLOSED，可选", "最多500条；含会员编号、昵称、问题内容、处理状态以及已发送给会员的客服回复"),
  "AdminController.updateFeedback": entry("更新反馈状态并回复会员", "{status,assignedTo?,replyContent?:2–2000字}；回复内容非空时记录当前管理员和回复时间", "反馈记录；会员端只可读取自己的反馈及回复，不返回后台管理员身份"),
  "AdminController.articles": entry("后台文章含草稿", undefined, "最多500条，含分类"),
  "AdminController.articleCategories": entry("后台文章分类", undefined, "分类数组；国际版含固定数字字符串categoryNo（如12），id/parentId仍为UUID，编号不随排序变化"),
  "AdminController.createArticleCategory": entry("新增分类", category, "分类记录；国际版含只读categoryNo，数据库自动分配，不接收客户端自选号"),
  "AdminController.updateArticleCategory": entry("编辑分类", category, "分类记录；当前为完整字段保存；国际版categoryNo保持不变，URL id与关联parentId仍为UUID"),
  "AdminController.createArticle": entry("新增文章", article, "Article"),
  "AdminController.updateArticle": entry("编辑文章", article, "Article；当前为完整字段保存"),
  "AdminController.integrations": entry("集成登记状态", undefined, "公开配置、是否已安全保存密钥、登记状态和检查时间；密钥永不回显，登记不等同实时连通"),
  "AdminController.updateIntegration": entry("维护集成登记和密钥", "{state:UNCONFIGURED/CONFIGURED/DISABLED/ERROR,publicConfig?,secrets?:对象,clearSecrets?:boolean}；secrets使用主机外置主密钥加密且只写不回显", "公开配置和hasSecret；不返回密钥内容"),
  "AdminController.audits": entry("审计记录", "page 默认1，每页100", "AuditLog[]"),
  "AdminController.warnings": entry("后台预警摘要", "page 默认1，每页100", "摘要数组，不含健康值"),
  "AdminController.notifications": entry("后台通知", "page 默认1，每页100", "通知列表；非主动群发接口"),
  "AdminController.legalDocuments": entry("协议版本列表", undefined, "LegalDocument[]"),
  "AdminController.createLegalDocument": entry("新增协议版本", legal, "LegalDocument"),
  "AdminController.updateLegalDocument": entry("编辑协议版本", legal, "LegalDocument"),
  "AdminController.adminUsers": entry("后台账号列表", undefined, "账号、角色、状态，不返回密码散列"),
  "AdminController.createAdmin": entry("新建后台账号", "{username,displayName,password:至少12字符,role}；角色见调用手册", "无密码账号信息"),
  "AdminController.updateAdmin": entry("编辑后台账号", "{displayName?,role?,active?}；当前不支持修改密码", "无密码账号信息"),
  "AdminController.deletionRequests": entry("注销任务列表", undefined, "注销任务及遮蔽会员资料；非手动执行删除接口"),
  "AdminController.settings": entry("客服与更新设置", undefined, "key=support/app_update 的设置数组"),
  "AdminController.updateSetting": entry("保存客服或更新设置", "key=support/app_update；{value:非空JSON对象,public?:boolean}；app_update 必须通过 DownloadManifest v1 校验", "设置对象；结构约定见调用手册"),
  "AdminController.commerceProducts": entry("总后台商品列表", "search可查商品名或ERP编号；page默认1", "主库商品、SKU及ERP库存快照；不直接改权威库存", "主库商城/聚水潭"),
  "AdminController.createCommerceProduct": entry("拒绝手工新增ERP商品", "请先通过聚水潭商品同步建立商品和SKU", "HTTP 400；不会创建第二套库存", "聚水潭"),
  "AdminController.quickUpdateCommerceProductSkus": entry("快速修改商品SKU售价与库存", "id=商品UUID；{skus:[{id:SKU UUID,updatedAt:当前更新时间,salePriceCents:整数分,stock:非负整数}]}；每次1至100条", "原子更新并返回商品；版本过期409且不部分保存；ERP商品后续同步可能覆盖手工值", "主库商城/聚水潭"),
  "AdminController.updateCommerceProduct": entry("编辑商品展示资料", "id=商品UUID；{displayName?,subtitle?,brand?,categoryId?,coverImage?,gallery?,detailHtml?,tags?,status?,featured?,sort?,localArchived?}", "展示资料；ERP编号、内部名称、SKU和库存不会被覆盖", "主库商城/聚水潭"),
  "AdminController.commerceCategories": entry("商城分类", "无请求体", "分类树平铺数据"),
  "AdminController.createCommerceCategory": entry("新增商城分类", "{name,parentId?,iconUrl?,sort?,enabled?}", "分类"),
  "AdminController.updateCommerceCategory": entry("编辑商城分类", "id=分类UUID；字段同新增", "分类"),
  "AdminController.commerceBanners": entry("商城首页轮播", "无请求体", "按排序返回的轮播图"),
  "AdminController.createCommerceBanner": entry("新增商城轮播", "{title,imageUrl,targetUrl?,sort?,enabled?}", "轮播图"),
  "AdminController.updateCommerceBanner": entry("编辑商城轮播", "id=轮播UUID；字段同新增", "轮播图"),
  "AdminController.commerceBusinessConfigs": entry("商城业务设置", "无请求体", "运费、客服等非密钥商城配置"),
  "AdminController.updateCommerceBusinessConfig": entry("保存商城业务设置", "key=配置键；{label?,value?,enabled?}", "商城配置；支付、ERP等密钥仍由集成中心管理"),
  "AdminController.commerceReviews": entry("商城评价管理", "无请求体", "真实订单评价、脱敏会员和商品摘要"),
  "AdminController.updateCommerceReview": entry("设置评价展示状态", "id=评价UUID；{published:boolean}", "评价；不能改写评分或正文"),
  "AdminController.commerceOrders": entry("总后台订单", "status可选；page默认1", "会员已脱敏的订单、明细、支付、物流和售后"),
  "AdminController.updateCommerceOrder": entry("维护订单备注", "id=订单UUID；{adminRemark?}；订单状态不能手工改写", "订单"),
  "AdminController.manuallySettleCommerceOrder": entry("待付款订单调价或登记线下收款", "id=订单UUID；仅SUPER_ADMIN；{action:ADJUST_PRICE|CONFIRM_OFFLINE_PAID,payableCents:正整数分,note:2–500字,orderVersion,idempotencyKey:8–120字符}", "更新后的订单、商品金额分摊和收款记录；重复同键同参数返回reused=true；异参、过期版本、非新系统订单、非待付款或渠道支付处理中均拒绝", "主库商城；线下收款只登记已核实结果，不调用或伪造第三方支付"),
  "AdminController.commerceAfterSales": entry("总后台售后", "status可选", "售后、退款及订单摘要"),
  "AdminController.updateCommerceAfterSale": entry("审核售后", "id=售后UUID；{status,returnLogisticsCompany?,returnTrackingNo?}", "售后；退款成功状态只能由真实回调完成", "支付/聚水潭"),
  "AdminController.commerceCoupons": entry("优惠券", "无请求体", "优惠券及领取数量"),
  "AdminController.createCommerceCoupon": entry("新增优惠券", "{name,value,minimumSpendCents,totalQuantity?,validFrom,validUntil,status?,employeeDistributable?,perEmployeeLimit?}", "优惠券；金额单位分"),
  "AdminController.updateCommerceCoupon": entry("编辑优惠券", "id=优惠券UUID；字段同新增", "优惠券"),
  "AdminController.commerceEmployees": entry("员工推广", "无请求体", "推广员工和钱包摘要；手机号遮蔽"),
  "AdminController.commerceCommissions": entry("奖金明细", "无请求体", "奖金规则、计提和历史只读流水"),
  "AdminController.commerceJobs": entry("商城集成任务", "status可选", "聚水潭等任务状态；未配置不伪报成功"),
  "AdminController.retryCommerceJob": entry("重试商城集成任务", "id=失败或死信任务UUID", "重新排队任务", "聚水潭"),
  "AdminController.queueProductSync": entry("安排聚水潭商品同步", "{modifiedBegin?,modifiedEnd?}；缺省最近24小时，最长31天", "幂等同步任务；任务成功才更新ERP商品与库存快照", "聚水潭"),
  "AdminController.queueFulfillmentSync": entry("安排聚水潭物流同步", "无请求体；同一小时幂等", "物流同步任务；任务成功才更新发货状态", "聚水潭"),
  "AdminController.payments": entry("统一支付流水", "status可选；page默认1", "商城订单、健康报告和健康会员支付单"),
  "AdminController.healthReports": entry("健康报告任务", "status可选", "报告任务、数据范围、生成版本和失败原因；不直接返回敏感原始数据"),
  "AdminController.retryHealthReport": entry("重试失败健康报告", "id=失败报告UUID", "重新排队且不重复扣次数", "AI供应商"),
  "AdminController.healthReportOffers": entry("健康报告价格方案", "无请求体", "全部历史版本及启用状态"),
  "AdminController.createHealthReportOffer": entry("新增健康报告价格版本", "{offerKey,title,description,entitlement,priceCents,creditCount,durationDays?,platforms,appleProductId?,active?,effectiveFrom?,effectiveUntil?}", "不可变的新价格版本；金额单位分"),
  "AdminController.updateHealthReportOffer": entry("发布价格方案新版本", "id=旧版本UUID；字段同新增", "停用旧版本并创建新版本，不原地改写历史价格"),
  "AdminController.notificationCampaigns": entry("营销通知任务", "无请求体", "草稿、计划、发送结果和失败数"),
  "AdminController.createNotificationCampaign": entry("创建营销通知草稿", "{name,type,title,body,deepLink?,audience:{allActive:true|userIds:[]},scheduledAt?}", "营销通知草稿；不会发送给未同意营销通知的会员"),
  "AdminController.updateNotificationCampaign": entry("编辑营销通知草稿", "id=草稿UUID；字段同新增", "营销通知草稿"),
  "AdminController.scheduleNotificationCampaign": entry("安排营销通知", "id=草稿UUID", "计划任务；实际发送由Worker完成并逐用户记录", "推送供应商"),
  "ApiDocumentationController.list": entry("接口中心路由与说明", "无请求体", "代码生成的方法/路径/鉴权/参数与可编辑业务说明；标记过期项"),
  "ApiDocumentationController.update": entry("编辑接口业务说明", "routeKey=控制器方法键；{title,summary,businessExample?,errorGuidance?,tags?,deprecated?,deprecationNote?}；不能修改方法和路径", "接口说明草稿", "代码生成路由目录"),
  "ApiDocumentationController.releases": entry("接口文档版本", "无请求体", "最近100个草稿、审核、已发布和归档版本"),
  "ApiDocumentationController.createRelease": entry("创建接口文档发布草稿", "{changeNote}；存在过期说明时拒绝", "冻结的脱敏文档快照"),
  "ApiDocumentationController.submit": entry("提交接口文档审核", "id=文档版本UUID", "IN_REVIEW版本"),
  "ApiDocumentationController.publish": entry("发布接口文档", "id=审核中文档版本UUID", "PUBLISHED版本；仅超级管理员"),
  "ApiDocumentationController.rollback": entry("恢复历史接口文档", "id=历史版本UUID；{changeNote?}", "新的已发布版本；路由签名不同时拒绝"),
  "ApiDocumentationController.export": entry("导出脱敏接口文档", "format=markdown/openapi", "Markdown文本或OpenAPI 3.1对象；Token、手机号和IP示例脱敏"),
  "CommerceCompatibilityController.requestSms": entry("商城短信登录验证码", "{mobile,usage?:login|bind_mobile}", "发送状态；只有非生产ALLOW_TEST_OTP显式启用时返回开发验证码", "短信供应商或隔离开发测试"),
  "CommerceCompatibilityController.loginPassword": entry("商城App账号密码登录", "{mobile,password,referralCode?}", "原商城raw会话{token,refreshToken,expiresAt,user}；复用App账号验证"),
  "CommerceCompatibilityController.authorizeWechatH5": entry("公众号网页授权地址", "{returnTo,codeChallenge:SHA256十六进制,referralCode?,consentVersion?,locale?}；国际版校验当前协议", "{authorizeUrl,state,expiresIn}；一次状态与固定同源回调", "独立公众号配置；国际H5开关；不复用小程序身份"),
  "CommerceCompatibilityController.loginWechatH5": entry("兑换公众号授权码", "{code,state,codeVerifier,consentVersion,locale?}", "global 已关联已验证手机号返回 raw 会话；仅已验证邮箱仍返回手机号登记票据。临时开关开启时可续登原微信的未验证手机登记账号", "微信公众号；当前已审核协议；身份冲突不合并资产，临时会话不能用于 App/交易"),
  "CommerceCompatibilityController.bindWechatH5Mobile": entry("验证手机号并绑定公众号身份", "{bindTicket,mobile,code,consentVersion}；短信usage=bind_mobile", "raw会话、requiresMobileBinding=false、returnTo", "短信+appId/OpenID范围身份"),
  "CommerceCompatibilityController.bindWechatH5Account": entry("国际H5绑定已验证账号", "{bindTicket,identifier,password,consentVersion,locale?}；邮箱或E.164手机号", "已验证手机返回 raw 会话；仅验证邮箱返回后续手机登记票据；不合并资产或修改账号密码", "仅global；已验证会员原密码；公众号独立配置和当前协议"),
  "CommerceCompatibilityController.requestWechatH5BindingCode": entry("国际H5申请身份绑定验证码", "{bindTicket,channel:email/sms,identifier,locale?}", "{challengeId,expiresIn,retryAfter,maskedIdentifier}；无验证码回显", "仅global；独立wechat_bind用途；邮件/短信真实渠道，未配置拒绝发送"),
  "CommerceCompatibilityController.bindWechatH5Code": entry("国际H5核验并绑定公众号", "{bindTicket,challengeId,code,password,consentVersion,locale?,nickname?}", "raw会员会话和站内returnTo；票据与验证码同事务一次消费", "仅global；账号冲突不合并；已有未验证账号需原密码与OTP双证明"),
  "CommerceCompatibilityController.storefrontCapabilities": entry("商城公开能力与维护状态", "无请求体", "登录、支付、积分和维护状态及不可用原因；global checkout含enabled/countryCodes:[CN]/currency:CNY/minimumCashCents；五H5支付渠道独立enabled/reason；不返回密钥", "真实配置、密钥、回调地址及出站/只读门禁共同决定支付就绪；未配置不开放；不代表已取得供应商回执；global登录与未核验/临时账号限制不变"),
  "CommerceCompatibilityController.requestWechatH5PhoneCode": entry("微信授权后申请手机号登记凭证", "{bindTicket,identifier:E.164手机号,locale?,expectedMode?:test}；自动申请临时凭证必须传expectedMode=test", "{challengeId,expiresIn,retryAfter,maskedIdentifier,mode:test/sms,sent,verificationRequired}；test不发短信、不返回已发送提示；expectedMode不符在发送前拒绝", "仅global；临时模式需独立显式开关；test用途不被注册/重置/原验证码绑定端点接受"),
  "CommerceCompatibilityController.bindWechatH5Phone": entry("微信手机号登记或核验后登录", "{bindTicket,challengeId,code:6位数字,consentVersion,locale?,password?}", "raw会话；user含phoneTestMode/phoneVerified/phoneVerificationStatus。临时模式接受任意6位数字但不验证手机号，仅原微信账号或未占用号码新建，冲突不合并", "test会话只准账号读取/退出/H5刷新，关闭开关即失效；正式短信才可标记手机号已验证"),
  "CommerceCompatibilityController.wechatH5Account": entry("读取H5当前会员安全资料", "Authorization: Bearer会员令牌", "raw安全会员资料；手机号掩码和真实核验状态；不返回其他会员或微信OpenID", "临时phone-test令牌只在此读接口/退出被接受；不能用于App、交易、健康或后台"),
  "CommerceCompatibilityController.payment": entry("查询本人支付状态", "id=支付单UUID", "raw支付记录；只有服务端确认成功才算付款完成"),
  "CommerceCompatibilityController.previewAfterSale": entry("商品售后资金预览", "id=订单UUID；{type,items:[{orderItemId,quantity}]}", "订单版本、商品现金退款、单列运费退款、积分返还；按原分摊累计数量差额"),
  "CommerceCompatibilityController.points": entry("本人积分抵扣余额与流水", "page从1开始，每页20条", "balanceCents未知为null，verified、items、pagination；不换算旧积分单位"),
  "CommerceCompatibilityController.returnLogistics": entry("登记本人售后寄回物流", "logisticsCompany、trackingNo、version；仅WAITING_RETURN退货退款或换货", "保存单号但保持待寄回状态；归属、版本校验，相同内容可幂等重试"),
  "AdminController.shippingRefundPreview": entry("核验独立退运费额度", "已支付订单ID；仅财务或超级管理员", "返回剩余运费、剩余现金、maximumCents与orderVersion；未知历史或进行中申请阻断"),
  "AdminController.createShippingRefund": entry("申请独立退运费", "amountCents、reason、requestKey、orderVersion；仅财务或超级管理员", "创建待审核SHIPPING_ONLY售后；审核后退款，不返积分、不冲商品佣金"),
  "CommerceCompatibilityController.loginSms": entry("商城短信登录", "{mobile,code,consentVersion,referralCode?}", "商城兼容会话；会员身份与主系统统一", "短信供应商"),
  "CommerceCompatibilityController.loginWechatMini": entry("商城小程序微信登录", "{code,consentVersion,referralCode?}", "商城兼容会话；未验证配置时返回暂不可用", "微信小程序"),
  "CommerceCompatibilityController.refresh": entry("轮换商城刷新令牌", "{refreshToken}", "新商城兼容会话"),
  "CommerceCompatibilityController.referral": entry("锁定商城推荐关系", "{referralCode}", "推荐关系；已有关系不覆盖"),
  "CommerceCompatibilityController.bootstrap": entry("商城首页初始化", "ref=员工推荐号，可选", "轮播、分类、精选商品、公开客服配置与capabilities", "主库商城"),
  "CommerceCompatibilityController.products": entry("商城商品列表", "page、pageSize、keyword、categoryId", "可售商品分页", "主库商城"),
  "CommerceCompatibilityController.product": entry("商城商品详情", "id=商品UUID", "商品、SKU和展示资料", "主库商城/聚水潭库存快照"),
  "CommerceCompatibilityController.cart": entry("商城购物车", "无请求体", "本人购物车"),
  "CommerceCompatibilityController.putCart": entry("更新商城购物车", "{skuId,quantity,selected?,mode?:set|increment}", "本人购物车；increment累计，默认set保留已有兼容性"),
  "CommerceCompatibilityController.deleteCart": entry("删除购物车项", "id=购物车项UUID", "空响应"),
  "CommerceCompatibilityController.addresses": entry("商城收货地址", "无请求体", "本人地址列表"),
  "CommerceCompatibilityController.saveAddress": entry("新增或兼容更新地址", address, "收货地址"),
  "CommerceCompatibilityController.updateAddress": entry("更新收货地址", "id=地址UUID；" + address, "收货地址"),
  "CommerceCompatibilityController.deleteAddress": entry("删除收货地址", "id=地址UUID", "空响应"),
  "CommerceCompatibilityController.previewOrder": entry("商城统一订单报价", order + "；couponClaimId、pointCents、buyerRemark、invoice可选", "兼容products/preview加整数分quote及fingerprint；券后分摊积分，不抵运费；现金至少1分；global仅CN收货/CNY，非CN地址400 delivery_country_unsupported，市场停用503 market_checkout_unavailable"),
  "CommerceCompatibilityController.createOrder": entry("商城创建订单", order + "；expectedQuote可选，取preview.quote.fingerprint", "单个真实主库订单；报价变化409 quote_changed且无资产写入，同键原参已创建优先返回原订单；global保存显式CN/CNY，市场与收货限制在积分/库存/券写入之前核验"),
  "CommerceCompatibilityController.orders": entry("商城订单列表", "status可选", "当前订单与旧订单只读投影"),
  "CommerceCompatibilityController.order": entry("商城订单详情", "id=订单UUID或旧订单映射", "订单详情；旧投影只读"),
  "CommerceCompatibilityController.cancelOrder": entry("取消待付款订单", "id=订单UUID", "{ok:true}"),
  "CommerceCompatibilityController.receiveOrder": entry("确认收货", "id=订单UUID", "{ok:true}"),
  "CommerceCompatibilityController.afterSale": entry("提交商城商品售后", "id=订单UUID；{type,reason,items:[{orderItemId,quantity}],orderVersion?,requestedCents?,description?,evidenceFileIds?:UUID[],evidenceImages?,idempotencyKey?}；新上传图片最多9个不同本人ID；global禁止非空外部evidenceImages", "售后记录占用可退数量，图片存file:UUID私有引用；同键同完整原请求优先恢复，换内容409；积分订单金额不能任意修改，现金确认后按行返积分；纯积分行审核后内部结算"),
  "CommerceEvidenceController.capabilities": entry("检查售后图片上传配置", "需会员Bearer会话；global须真实验证邮箱或手机号，临时手机登记会话不可用", "raw JSON {enabled,maxFiles:9,maxBytes:10485760,contentTypes,reason?}；配置缺失返回enabled=false；只检查配置，不代表真实存储回执", "私有object_storage配置；不返回密钥、桶名或公开链接"),
  "CommerceEvidenceController.upload": entry("上传本人售后图片", "multipart/form-data字段file；每请求1张JPEG/PNG/WebP，实际大小≤10MiB；每分钟12次；会员Bearer认证，global临时会话拒绝", "HTTP201 raw JSON {id,byteSize,contentType,sha256}；只返回FileObject UUID，不返回公开URL；无文件/类型伪装400，超限413，过频429，未配置或存储失败503", "私有object_storage；成功上传不是售后申请，申请另传evidenceFileIds"),
  "CommerceEvidenceController.image": entry("读取本人私有售后图片", "id=本人ACTIVE、commerce_after_sale用途文件UUID；会员Bearer放请求头，不放URL", "HTTP200原始二进制image/jpeg、image/png或image/webp，不含JSON包裹；private,no-store及nosniff；他人文件/不存在404，未登录或global临时会话401，存储失败503", "私有object_storage；不能通过公开头像地址读取"),
  "AdminCommerceEvidenceController.image": entry("后台授权查看售后证据图片", "saleId=售后UUID，fileId=该售后实际关联的文件UUID；后台Bearer和commerce-after-sales/read权限", "HTTP200原始JPEG/PNG/WebP二进制，不含data或公开URL；校验订单会员文件归属并成功写COMMERCE_EVIDENCE_READ审计后返回；权限403、未关联404、存储503；审计失败不返回图片", "私有object_storage与强制读取审计；角色沿用后台售后读取权限"),
  "CommerceCompatibilityController.logistics": entry("商城订单物流", "id=订单UUID", "物流公司、单号和轨迹"),
  "CommerceCompatibilityController.favorites": entry("商城收藏列表", "无请求体", "本人收藏商品"),
  "CommerceCompatibilityController.favorite": entry("收藏或取消商品", "productId=商品UUID；{enabled:boolean}", "保存结果"),
  "CommerceCompatibilityController.coupons": entry("商城优惠券", "无请求体", "本人可用及历史券"),
  "CommerceCompatibilityController.availableCoupons": entry("商城领券中心", "page=页码，默认1，每页20；会员鉴权", "公开有效券、本人是否已领、是否还有额度；不暴露员工赠券库存"),
  "CommerceCompatibilityController.claimCoupon": entry("领取优惠券", "id=优惠券UUID", "领取记录；重复领取幂等"),
  "CommerceCompatibilityController.claimCouponByCode": entry("输入优惠码领取优惠券", "{code:4-32位字母、数字、_或-；服务端统一转大写}", "本人领取记录；仅匹配后台启用且有效的唯一优惠码，错误不泄露券状态"),
  "CommerceCompatibilityController.feedback": entry("商城会员读取自己的反馈与客服回复", "会员Bearer会话", "最多100条，仅按当前登录userId返回；含问题、状态、replyContent和repliedAt，不返回后台管理员身份"),
  "CommerceCompatibilityController.submitFeedback": entry("商城会员提交问题反馈", "{category,content:5–2000字,contact?:联系方式,attachments?:本人有效文件UUID数组}", "{id,status}；服务端绑定当前登录会员，不能代替他人提交", "主库客服反馈"),
  "CommerceCompatibilityController.review": entry("商城商品评价", "{orderItemId,rating,content,images?}", "评价记录"),
  "CommerceCompatibilityController.createPayment": entry("商城创建统一支付单", "{orderId,channel,idempotencyKey?}", "支付单及渠道调用参数；不等于支付成功；global仅CNY商城订单的wechat_jsapi/wechat_h5/wechat_native/alipay_wap/alipay_page", "未配置或出站暂停返回503；global JSAPI必须当前公众号绑定且ACTIVE、邮箱或手机号已真实验证；临时任意码账号禁止交易；商户/验签/回调完整性在资金关系创建前与出站前复验"),
  "CommerceCompatibilityController.wechatNotify": entry("兼容微信支付回调", "微信支付签名头和密文通知", "微信约定确认响应", "微信支付"),
  "CommerceCompatibilityController.wechatRefundNotify": entry("兼容微信退款回调", "微信支付签名头和密文通知", "微信约定确认响应", "微信支付"),
  "CommerceCompatibilityController.alipayNotify": entry("兼容支付宝回调", "支付宝表单参数", "success/failure文本", "支付宝"),
  "CommerceEmployeeController.authorizeUrl": entry("生成企业微信员工登录地址", "redirectUri必须是后台允许的HTTPS域名", "企业微信OAuth地址；不代表已登录", "企业微信；未配置返回503"),
  "CommerceEmployeeController.oauth": entry("企业微信员工登录", "{code}；仅接受企业微信返回的一次性登录码", "独立员工会话和脱敏员工摘要", "企业微信；未配置返回503"),
  "CommerceEmployeeController.dashboard": entry("员工推广业绩", "range=today|7d|30d|month|custom；from/to为YYYY-MM-DD；page/pageSize", "服务端日期统计与订单分页，奖金冻结/可用/提现中分列，未取得钱包为null；时间口径独立标注", "主库商城"),
  "CommerceEmployeeController.promotion": entry("生成员工推广素材", "productId可选商品UUID", "推荐链接、二维码和海报；链接不改变顾客或员工身份", "COMMERCE_STOREFRONT_URL商城地址配置"),
  "CommerceEmployeeController.coupons": entry("员工可分发优惠券", "无请求体", "可领取额度、赠券码和状态；历史链接不回显", "主库商城"),
  "CommerceEmployeeController.claimCoupons": entry("领取员工赠券码", "id=优惠券UUID；{quantity?}受批次和员工限额约束", "一次性返回赠券链接与二维码；原始令牌不落库", "主库商城"),
  "CommerceEmployeeController.gift": entry("查看员工赠送的优惠券", "token=高熵一次性赠券令牌", "优惠券、员工摘要和领取状态；不返回会员信息", "主库商城"),
  "CommerceEmployeeController.redeemGift": entry("会员领取员工赠券", "token=赠券令牌；需会员登录", "本人优惠券领取记录；并发领取只成功一次", "主库商城"),
};
