// Hand-reviewed semantics. Route, method, auth and parameter locations come from TS decorators.
const entry = (summary, request = "无请求体", response = "对象", dependency = "核心服务") => ({ summary, request, response, dependency });
const formProfile = "Profile：nickname、head_portrait/avatarUrl、sex/gender、birthday、height/heightCm、weight/weightKg；仅提交需修改字段";
const healthQuery = "date/day=YYYY-MM-DD 或时间戳；selectmember/selectMemberId=被关爱人的数字 ID（缺省自己）；page 从 1 开始；type 见调用手册";
const composition = "JSON {data:{date?,...指标标量}}；建议提供采集时间和 Idempotency-Key；无二者不能保证重试去重";
const push = "PushInstallation：installationId、platform、registrationId、appVersion、buildNumber；字段别名见调用手册";
const address = "Address：name/realname、mobile、province/city/district、detail/address_details、isDefault/is_default；旧地区码字段见调用手册";
const order = "Order：addressId/address_id、items:[{skuId/sku_id,quantity/num}]；旧单品可用 data=JSON 字符串；每次新购买使用新的 Idempotency-Key";
const mall = "商城服务及内部身份凭据；支付还依赖支付渠道配置";
const category = "{name,parentId?,sort?,enabled?}；parentId 使用分类 UUID";
const article = "{title,contentHtml,summary?,coverUrl?,categoryId?,status?:DRAFT/PUBLISHED/ARCHIVED,publishedAt?}；categoryId 为 UUID";
const legal = "{documentType,version,title,contentHtml,active,publishedAt?}；同类型仅一个激活版本";
const healthBatch = "HealthBatch：JSON {records:[...]}，1–200 条；Idempotency-Key 8–160 字符必填；详细记录结构见调用手册";
const batchResult = "{acceptedIds,rejected:[{id,code,message}],nextCursor}；HTTP 成功不代表全部记录接收";
export const notes = {
  "StatusController.live": entry("进程存活", undefined, "{status,service,revision}"),
  "StatusController.ready": entry("数据库就绪", undefined, "{status,database,revision}；失败 HTTP 503；不证明供应商可用"),
  "AuthController.register": entry("兼容无短信注册", "{mobile,password,nickname?,consentVersion}；上线前必须解决手机号所有权验证，见缺陷清单", "Session"),
  "AuthController.login": entry("密码登录", "{mobile/username,password}", "Session"),
  "AuthController.requestSms": entry("发送验证码", "{mobile,usage:register/reset_password}", "发送状态；不返回验证码", "短信供应商"),
  "AuthController.registerWithSms": entry("短信注册", "{mobile,code,password,nickname?,consentVersion}", "Session", "短信供应商"),
  "AuthController.resetPassword": entry("短信重置密码", "{mobile,code,password/newPassword}", "Session；旧会话失效", "短信供应商"),
  "AuthController.refresh": entry("轮换刷新令牌", "{refreshToken}；客户端必须串行刷新并替换旧令牌", "Session"),
  "AuthController.logout": entry("退出当前会话", undefined, "{loggedOut:true}"),
  "AuthController.deleteAccount": entry("提交账号注销申请", undefined, "注销任务；并非立即删除全部数据"),
  "MembersController.profile": entry("本人资料", undefined, "Profile；V2 id 为 UUID，不是 V1 数字会员 ID"),
  "MembersController.saveProfile": entry("修改本人资料", formProfile, "Profile"),
  "MembersController.goals": entry("活动目标", undefined, "{steps,distanceMeters,caloriesKcal}；未知为 null"),
  "MembersController.saveGoals": entry("保存活动目标", "{steps,distanceMeters,caloriesKcal}；缺省字段置 null，客户端应提交完整目标", "活动目标"),
  "HealthController.ingestBatch": entry("健康批量同步", healthBatch, batchResult),
  "HealthController.list": entry("本人健康历史", "metric=规范指标；limit 默认 50 最大 200；before=上页 nextCursor", "{items,nextCursor}；同时间戳分页限制见缺陷清单"),
  "HealthController.warningRules": entry("读取阈值提醒", undefined, "规则数组；未获取阈值为 null"),
  "HealthController.warnings": entry("读取提醒事件", "limit 默认 50", "提醒数组；仅阈值提醒，不是诊断"),
  "HealthController.saveWarningRules": entry("保存阈值提醒", "{rules:[{metric,enabled,lowThreshold?,highThreshold?,secondaryHighThreshold?,shareWithCare?}]}；目前仅本人的提醒闭环", "保存后的规则数组"),
  "DevicesController.list": entry("已绑定设备", undefined, "Device[]；只含未解绑设备"),
  "DevicesController.bind": entry("绑定设备快照", "{deviceId/hardwareId,vendor,model,displayName/name,firmware?,capabilities?:string[],syncCursor?}", "Device；不是服务端蓝牙连接"),
  "DevicesController.updateCapabilities": entry("更新设备能力及游标", "{capabilities:string[],firmware?,syncCursor?}；id=绑定记录 UUID", "Device"),
  "DevicesController.unbind": entry("解绑设备", "id=绑定记录 UUID", "{unbound:true}；保留历史健康数据"),
  "CareController.relationships": entry("关爱关系列表", undefined, "CareRelationship[]，含 direction、双方昵称、授权指标"),
  "CareController.invite": entry("邀请查看对方健康数据", "{mobile}；不能自邀；已生效返回 409；待处理重复请求不重复发通知", "CareRelationship"),
  "CareController.respond": entry("接受或拒绝邀请", "id=关系 UUID；{accepted:boolean}；仅收件人可操作", "CareRelationship；接受后仍需逐指标授权"),
  "CareController.savePermissions": entry("共享本人指标", "id=关系 UUID；{metrics:规范指标数组,expiresAt?:ISO8601}；仅数据所属人；[] 撤销全部指标", "CareRelationship"),
  "CareController.revoke": entry("撤销关爱关系", "id=关系 UUID；任一参与方可撤销", "CareRelationship；撤销后不能查询"),
  "CareController.preview": entry("按授权查看健康数据", "id=关系 UUID；metric 必填；from/to=ISO8601；缺省近 7 天；左闭右开", "HealthRecord[]；逐指标授权并记录审计，拒绝 403"),
  "NotificationsController.list": entry("消息列表", "page 默认 1；pageSize 默认 30", "分页消息"),
  "NotificationsController.unread": entry("未读数", undefined, "{count}"),
  "NotificationsController.detail": entry("消息详情", "id=消息 UUID", "Notification；V2 GET 不标记已读"),
  "NotificationsController.markRead": entry("标记消息已读", "id=消息 UUID/eventId", "{read:true}；仅本人消息"),
  "NotificationsController.register": entry("登记推送安装", push, "安装记录；登记不等于推送成功", "推送供应商（登记可独立使用）"),
  "NotificationsController.unregister": entry("撤销本人推送安装", "installationId=安装标识", "撤销结果"),
  "ContentController.categories": entry("文章分类", "parentId 可选 UUID；缺省顶级", "ArticleCategory[]"),
  "ContentController.articles": entry("已发布文章", "categoryId 可选 UUID；page 默认 1；pageSize 默认 20 最大 50", "{items,total,page,pageSize}"),
  "ContentController.article": entry("文章详情", "id=UUID 或迁移的旧文章 ID", "Article；未发布/未来发布 404"),
  "ContentController.legal": entry("协议文档", "type=文档类型；version 可选，不传取当前激活版本", "LegalDocument；未发布 404"),
  "AiController.history": entry("本人 AI 历史", "sessionId 可选客户端会话标识", "最近 20 个会话及消息"),
  "AiController.send": entry("AI 提问", "{content/message,sessionId?}；正文 1–4000 字符", "{id,conversationId,role,content,createdAt}", "AI 供应商；未配置返回 503"),
  "SupportController.config": entry("客服配置", undefined, "客服配置或未配置状态"),
  "SupportController.appUpdate": entry("App 更新配置", undefined, "更新清单或未配置状态"),
  "SupportController.feedback": entry("提交反馈", "{content:5–2000字符,category?,contact?:最多100字符,attachments?:本人文件ID数组最多6项}", "{id,status}"),
  "FilesController.upload": entry("上传图片", "multipart file；purpose=avatar/feedback；最大 10 MiB；JPEG/PNG/WebP", "{id,url,...}", "私有对象存储"),
  "FilesController.uploadEcg": entry("上传 ECG 压缩文件", "multipart file + sha256；最大 25 MiB；gzip；先上传再提交 HealthBatch 引用", "ECG 对象键和摘要；原始波形非公开", "私有对象存储"),
  "FilesController.download": entry("获取公开头像", "id=文件 UUID；仅 ACTIVE 且 purpose=avatar 的文件", "原始文件流，不包裹 JSON；反馈/ECG 不可经此接口下载", "对象存储"),
  "CommerceController.home": entry("商城首页", undefined, "现商城 bootstrap", mall),
  "CommerceController.products": entry("商城商品列表", "page、pageSize、keyword 等查询参数透传商城", "现商城商品分页", mall),
  "CommerceController.product": entry("商城商品详情", "id=现商城商品 ID", "现商城商品及 SKU", mall),
  "CommerceController.cart": entry("购物车", undefined, "现商城购物车", mall),
  "CommerceController.putCart": entry("更新购物车项", "{skuId,quantity,selected?}", "现商城购物车", mall),
  "CommerceController.deleteCart": entry("删除购物车项", "id=购物车项 ID", "商城删除结果", mall),
  "CommerceController.addresses": entry("地址列表", undefined, "Address[]", mall),
  "CommerceController.address": entry("地址详情", "id=商城地址 ID", "Address", mall),
  "CommerceController.saveAddress": entry("新增地址", address, "Address", mall),
  "CommerceController.updateAddress": entry("更新地址", address, "Address", mall),
  "CommerceController.deleteAddress": entry("删除地址", "id=商城地址 ID", "{deleted:true}", mall),
  "CommerceController.orders": entry("当前订单与历史投影", "status=商城订单枚举，可选", "Order[]；source=mall/legacy，readOnly=true 的订单只读；商城故障时降级限制见缺陷清单", mall),
  "CommerceController.order": entry("订单详情", "id=现商城 ID 或旧投影/旧订单 ID", "Order", mall),
  "CommerceController.createOrder": entry("多商品创建单个商城订单", order, "Order；不重放旧订单", mall),
  "CommerceController.receipt": entry("确认收货", "id=现商城订单 ID", "{received:true}；旧订单拒绝 409", mall),
  "CommerceController.afterSales": entry("申请售后", "id=现商城订单 ID；{type,reason,...} 按商城售后契约", "现商城售后结果；旧订单拒绝 409", mall),
  "CommerceController.logistics": entry("订单物流", "id=现商城订单 ID", "物流轨迹数组", mall),
  "CommerceController.payment": entry("生成 App 支付参数", "{orderId,channel:wechat_app/alipay_app}；金额以商城订单为准；幂等头透传", "{paymentNo,channel,invoke}；不等于付款成功", mall),
  "LegacySiteController.login": entry("旧版密码登录", "表单 username/mobile、password", "LegacySession"),
  "LegacySiteController.register": entry("旧版注册", "表单 mobile/username、password、nickname?、consent_version?、code?；无 code 路径的上线限制见缺陷清单", "LegacySession"),
  "LegacySiteController.smsCode": entry("旧版短信验证码", "表单 mobile、usage=register/reset/forgot/up-pwd/reset_password", "发送状态", "短信供应商"),
  "LegacySiteController.resetPassword": entry("旧版重置密码", "表单 mobile、code、password", "LegacySession", "短信供应商"),
  "LegacySiteController.refresh": entry("旧版刷新", "表单 refresh_token", "LegacySession"),
  "LegacySiteController.logout": entry("旧版退出", undefined, "{logged_out:true}"),
  "LegacyMemberController.member": entry("旧版本人资料", undefined, "LegacyProfile：数字 id、uuid、mobile、nickname、head_portrait 等"),
  "LegacyMemberController.saveMember": entry("旧版修改资料", formProfile, "LegacyProfile"),
  "LegacyMemberController.goals": entry("旧版活动目标", undefined, "{steps,juli,reliang}"),
  "LegacyMemberController.saveGoals": entry("旧版保存目标", "表单 steps、juli(米)、reliang(kcal)", "规范目标对象；以重新读取为准"),
  "LegacyMemberController.healthBatch": entry("旧前缀批量健康同步", healthBatch + "；V1 缺少幂等头时使用请求摘要", batchResult),
  "LegacyMemberController.saveActivity": entry("旧版当日活动快照", "{steps_num,reliang_num,juli_num}；无采集日期，仅作接收当日快照，不能回填过去日期", batchResult),
  "LegacyMemberController.saveDaily": entry("旧版日健康同步", "JSON {dailyDate:[{date,heartReat?,pulseReat?,bloodPressure?,bloodOxygen?,...}]}；1–2000 行，展开后分批；见调用手册", batchResult + "；任意拒绝时业务 400，不伪报全部成功"),
  "LegacyMemberController.dailyPreview": entry("旧版健康预览", healthQuery, "LegacyDaily[]；同一小时多条记录保留；最多 20000 条，超出要求缩小范围"),
  "LegacyMemberController.dailyHistory": entry("小程序健康历史列表", healthQuery, "LegacyDaily[]；按 30 条规范记录分页，无日期时查历史"),
  "LegacyMemberController.bloodHistory": entry("小程序血液成分历史", healthQuery, "[{id,date,...指标}]，每页 30 条"),
  "LegacyMemberController.saveBodyComposition": entry("旧版身体成分同步", composition, batchResult),
  "LegacyMemberController.previewBodyComposition": entry("旧版身体成分预览", healthQuery, "[{id,date,...指标}]"),
  "LegacyMemberController.saveBloodComposition": entry("旧版血液成分同步", composition, batchResult),
  "LegacyMemberController.previewBloodComposition": entry("旧版血液成分预览", healthQuery, "[{id,date,...指标}]"),
  "LegacyMemberController.saveEcg": entry("旧版 ECG 同步", "JSON {data:{date,sampleFrequency?,...摘要},totalArray:采样数组}；先压缩存储再写摘要", batchResult, "对象存储"),
  "LegacyMemberController.previewEcg": entry("旧版 ECG 摘要历史", healthQuery, "[{id,date,...摘要,ecgArtifact?}]；波形下载尚未闭环"),
  "LegacyMemberController.bodyDetail": entry("小程序身体成分单条", "id=本人 clientRecordId 或 UUID", "{id,date,...指标}；非本人 404"),
  "LegacyMemberController.careInvitations": entry("旧版关爱关系", undefined, "LegacyCare[]：数字关系及成员 ID、examine_status、setting"),
  "LegacyMemberController.careMembers": entry("旧版已关爱成员", undefined, "本人发出的已生效 LegacyCare[]"),
  "LegacyMemberController.addCare": entry("旧版发出邀请", "{mobile}", "规范 CareRelationship；旧页面随后刷新列表获取数字 ID"),
  "LegacyMemberController.respondCare": entry("旧版处理邀请", "{id:数字关系ID,examine_status:1接受/其他拒绝}", "CareRelationship"),
  "LegacyMemberController.careSettings": entry("旧版读取共享范围", "to_member_id=另一方数字成员 ID", "{setting:JSON字符串}；值使用 heartReat/bloodPressure 等旧拼写"),
  "LegacyMemberController.saveCareSettings": entry("旧版保存共享范围", "{to_member_id,setting:数组或JSON字符串}；仅数据本人可修改；未知指标拒绝", "CareRelationship"),
  "LegacyMemberController.carePreview": entry("旧版关爱汇总", "id=数字关系 ID；date/day 可选", "{daily:LegacyDaily[],jrjk:{steps_num,juli_num,reliang_num}}；未授权指标不返回，未知 null"),
  "LegacyMemberController.notificationList": entry("旧版消息列表", "page 默认 1，每页 30", "LegacyNotification[]"),
  "LegacyMemberController.unread": entry("旧版消息未读数", undefined, "{unread_count}"),
  "LegacyMemberController.notificationStatistics": entry("旧版消息分类未读数", undefined, "{announce_count,remind_count,unread_count}"),
  "LegacyMemberController.notification": entry("旧版消息详情并标已读", "id=数字 ID/UUID/eventId", "LegacyNotification；GET 有兼容副作用，不适合缓存或预取"),
  "LegacyMemberController.readNotification": entry("旧版标记已读", "id=数字 ID/UUID/eventId", "已读结果"),
  "LegacyMemberController.pushDevice": entry("旧版登记推送安装", push, "安装记录", "推送供应商（登记可独立使用）"),
  "LegacyMemberController.removePushDevice": entry("旧版撤销安装", "installationId", "撤销结果"),
  "LegacyMemberController.deleteAccount": entry("旧版提交注销", undefined, "注销任务"),
  "LegacyContentController.categories": entry("旧版文章分类", "pid=旧分类 ID/UUID", "[{id,pid,title,name,sort}]；新增分类数字 ID 兼容缺口见缺陷清单"),
  "LegacyContentController.articles": entry("旧版文章列表", "cate_id=旧分类 ID/UUID；page 默认 1，每页 20", "LegacyArticle[]；新增文章 ID 兼容缺口见缺陷清单"),
  "LegacyContentController.article": entry("旧版文章详情", "id=迁移旧文章 ID/UUID", "LegacyArticle"),
  "LegacyContentController.single": entry("旧版单页文章/协议", "id=原单页文章 ID；当前查询 Article，尚未映射 LegalDocument", "LegacyArticle；协议映射缺口见缺陷清单"),
  "LegacyContentController.aiHistory": entry("旧版 AI 历史", "session_id 可选", "[{id,session_id,role,message,content,created_at}]"),
  "LegacyContentController.sendAi": entry("旧版 AI 提问", "JSON/表单 message、session_id?", "{id,session_id,role,message,content,created_at}", "AI 供应商"),
  "LegacyPagesController.page": entry("旧版商城首页结构", "code 可选", "{code,items}；swiper/tabs 商品结构", mall),
  "LegacyProductController.product": entry("旧版商品详情", "id=首页返回的数字商品 ID", "LegacyProduct（数字 SKU、价格元、库存）", mall),
  "LegacyOrderController.orders": entry("旧版订单列表", "synthesize_status=0待付/1待发/2待收/3完成/4取消/-1售后/-3退款，可选", "LegacyOrder[]；read_only 标明历史订单", mall),
  "LegacyOrderController.order": entry("旧版订单详情", "id=数字订单 ID", "LegacyOrder", mall),
  "LegacyOrderController.preview": entry("旧版下单预览", order + "；GET 查询参数", "{address,products,...金额}", mall),
  "LegacyOrderController.createOrder": entry("旧版创建订单", order, "LegacyOrder；响应不是支付成功", mall),
  "LegacyOrderController.createBatchOrder": entry("旧版多商品单订单", order, "单个 LegacyOrder，非逐商品拆单", mall),
  "LegacyOrderController.receipt": entry("旧版确认收货", "表单 id=数字订单 ID", "确认结果；历史订单拒绝 409", mall),
  "LegacyOrderController.refund": entry("旧版申请售后", "表单 id=数字订单项ID，type、reason 等按商城约定", "售后结果", mall),
  "LegacyOrderController.express": entry("旧版物流详情", "order_id=数字订单ID", "{data:物流轨迹数组}", mall),
  "LegacyAddressController.list": entry("旧版地址列表", undefined, "LegacyAddress[]", mall),
  "LegacyAddressController.detail": entry("旧版地址详情", "id=数字地址 ID", "LegacyAddress", mall),
  "LegacyAddressController.create": entry("旧版新增地址", address, "LegacyAddress", mall),
  "LegacyAddressController.update": entry("旧版更新地址", address, "LegacyAddress", mall),
  "LegacyAddressController.remove": entry("旧版删除地址", "id=数字地址 ID", "删除结果", mall),
  "LegacyPaymentController.create": entry("旧版生成支付参数", "multipart pay_type=1微信/2支付宝（兼容100/101）、trade_type=app、order_group=order、data=JSON字符串含order_id；不相信客户端金额", "{payment_no,channel,config}；订单状态以服务端回查为准", mall),
  "LegacyFilesController.upload": entry("旧版上传头像", "multipart file，JPEG/PNG/WebP，最大 10 MiB", "{id,url,path,...}；path 与 url 相同", "对象存储"),
  "AdminLoginController.login": entry("后台登录", "JSON {username,password}", "AdminSession；不能与 App Token 混用"),
  "AdminController.logout": entry("后台退出", undefined, "{loggedOut:true}"),
  "AdminController.dashboard": entry("运营概览", undefined, "会员/健康/关爱/预警/反馈/积压数量"),
  "AdminController.members": entry("会员查询", "search 查昵称/手机号/旧会员ID；page 默认1；pageSize 默认30 最大100", "{items,total,page,pageSize}；手机号遮蔽"),
  "AdminController.healthSummary": entry("会员健康数量摘要", "id=会员 UUID", "按指标数量与首末采集时间"),
  "AdminController.rawHealth": entry("授权查看原始健康记录", "id=会员 UUID；limit 默认100 最大500", "HealthRecord[]；留下专门读取审计"),
  "AdminController.care": entry("后台关爱关系", undefined, "最多500条，双方昵称和指标权限；尚无分页"),
  "AdminController.devices": entry("后台设备快照", undefined, "最多500条；尚无分页"),
  "AdminController.feedback": entry("反馈工单", "status=OPEN/IN_PROGRESS/RESOLVED/CLOSED，可选", "最多500条"),
  "AdminController.updateFeedback": entry("更新反馈处理状态", "{status,assignedTo?}", "反馈记录"),
  "AdminController.articles": entry("后台文章含草稿", undefined, "最多500条，含分类"),
  "AdminController.articleCategories": entry("后台文章分类", undefined, "分类数组"),
  "AdminController.createArticleCategory": entry("新增分类", category, "分类记录"),
  "AdminController.updateArticleCategory": entry("编辑分类", category, "分类记录；当前为完整字段保存"),
  "AdminController.createArticle": entry("新增文章", article, "Article"),
  "AdminController.updateArticle": entry("编辑文章", article, "Article；当前为完整字段保存"),
  "AdminController.integrations": entry("集成登记状态", undefined, "公开配置、登记状态和检查时间；不等同实时连通结果"),
  "AdminController.updateIntegration": entry("维护集成登记", "{state:UNCONFIGURED/CONFIGURED/DISABLED/ERROR,publicConfig?,secretRef?}；不得填密钥，配置不直接注入进程环境", "公开集成登记"),
  "AdminController.audits": entry("审计记录", "page 默认1，每页100", "AuditLog[]"),
  "AdminController.warnings": entry("后台预警摘要", "page 默认1，每页100", "摘要数组，不含健康值"),
  "AdminController.notifications": entry("后台通知", "page 默认1，每页100", "通知列表；非主动群发接口"),
  "AdminController.legalDocuments": entry("协议版本列表", undefined, "LegalDocument[]"),
  "AdminController.createLegalDocument": entry("新增协议版本", legal, "LegalDocument"),
  "AdminController.updateLegalDocument": entry("编辑协议版本", legal, "LegalDocument"),
  "AdminController.adminUsers": entry("后台账号列表", undefined, "账号、角色、状态，不返回密码散列"),
  "AdminController.createAdmin": entry("新建后台账号", "{username,displayName,password:至少12字符,role}；角色见调用手册", "无密码账号信息"),
  "AdminController.updateAdmin": entry("编辑后台账号", "{displayName?,role?,active?}；当前不支持修改密码", "无密码账号信息"),
  "AdminController.deletionRequests": entry("注销任务列表", undefined, "注销任务及遮蔽会员资料；非手动执行删除接口"),
  "AdminController.settings": entry("客服与更新设置", undefined, "key=support/app_update 的设置数组"),
  "AdminController.updateSetting": entry("保存客服或更新设置", "key=support/app_update；{value:非空JSON对象,public?:boolean}", "设置对象；结构约定见调用手册"),
};
